In [2]:
import pandas as pd
import numpy as np
from modules import *
from nltk.corpus import stopwords
from nltk.stem.porter import *
from nltk import word_tokenize
from konlpy.tag import Okt
from nltk.util import everygrams

In [3]:
#원하는 태그 추출 & 불용어 제거
okt = Okt()

#불용어
stopwords = pd.read_csv('ko-stopwords.csv') #한국어불용어사전 불러오기
stopwords=list(stopwords['stopwords']) 
stopwords.extend(['에서','고','이다','는','한','씨', "것","거","게","데","이다","건","고","되다","되어다","걸","기",
                  "시","네","듯","랍니","중이","얘","스","도도", "나","수","개","내","기","제","저","인","있다","이렇다",
                  "그렇다","번","위","팅","분","인","링","란","포","두", "진짜", "하다" ,"이다" ,"가다", "이제" ,"들다",
                 '에서','고','이다','젛','뇨','껀데','뭘'
                 ,'최고','느리다','마을','최고','항상','포장','재다','말다','목','넘김','만족하다','정말','역시','아주','감사하다','오다','자주','요','늘','넘다','않다','더','병','다','숙성','나다','술','드리다','마트','꼼꼼하다','잇다'
                 ,'복','순도','용','비싸다','가격','많다','강하다','보내다','추천','보고','쏘다','느낌','사다','처음','많이','톡','생각','엄청','날','아니다'
                 ,'믿다', '구입', '사먹다', '한번', '싶다', '콤', '완전', '제품', '재', '해주다', '말', '사람','특별하다','언제나','빨르다','두번째','전','계속','달'
                 ,'추석', '인생', '최애', '명절', '해', '중', '생각나다', '시원하다', '다르다', '알다', '가족', '정도', '기대', '친구', '괜찮다', '부모님', '지인', '아직'
                 ,'만족스럽다', '빼다', '상품', '굿', '못', '도', '기분', '다시', '주다', '즐기다', '맞다', '맛보다', '제일', '집', '입맛', '모르다', '먹기'
                 ,'조심하다', '따다', '차다', '엄마', '예정', '만족', '감', '일반', '파다', '막', '근데', '별로', '적당하다','예전', '가끔', '유명하다', '만', '뚜껑', '매우', '기대하다', '의사', '한잔', '신선하다', '느끼다', '그냥', '아쉽다'
                 ,'오픈', '쎄다', '여자', '호불호', '꼭', '벌써', '버리다', '이렇게', '돼다', '크다', '느껴지다','고급', '종종', '어울리다', '알', '남편', '빨리', '어른', '소문', '아버지', '마시기', '할인', '살다' 
                 ,'풍부하다', '모임', '해드리다', '빠지다', '나서다', '원래', '아빠', '걸리다', '안', '도착', '없이'
                 ,'하루', '딱이다', '상태', '향', '후', '설', '주변', '사서', '때문', '반하다', '연말'
                 ,'해봤다', '강추', '찾다', '자꾸', '살짝', '몇번', '빨', '요즘', '신세계', '사진', '생일'
                 ,'빠르다', '자다', '구매', '마시다', '받다', '보다', '없다', '새다', '숙취', '아스파탐', '대포', '넘어가다','주가'
                 ,'지나다', '무', '머리', '편하다', '아프다', '두다', '인터넷', '택배', '숙성하다', '일주일', '봄', '배달', '만들다', '애용', '냉장고' 
                 ,'여름', '잔', '앞', '며칠', '팔다', '달라지다', '가장', '변하다', '번창', '안전하다', '젤', '배상면', '건강하다', '굿굿'
                 ,'따르다', '이용', '확실하다', '날짜', '시중', '들어가다', '첨가', '유통', '아이스팩', '제조', '넣다', '생', '다양하다','종류','들어가다','전통주','마켓','술술','후기','사보다','부담','여러가지','리뷰','블루'
                 ,'인기','궁금하다','대상','무난','취향','적다','단','평이','이용','터지다','맘'
                 ]
                 +'프로 특유 깨다 담 더락 프로 석식 듭니 듭니다 온라인 회랑 회 따뜻하다 나쁘다 튼튼하다 끄다 끝 장인어른 일품 파손 싸다 술맛 비다 착하다 명인 증류 안동소주 안동 뒤끝 박다 신랑 비다 뒤끝 품질 짜다 용이 외국인 지고 지다 높다 어르신 신분 명인 보이다 준비 쇼핑 밤 서울 실향 스컬 낮다 가볍다 섞다 귀엽다 명랑 버전 꼼꼼 볼 대중 패키지 높다 하이 널 타 써다 집들이 실향 원주 긋다 술맛 술집 패키지 결의 증류주 섞다 타 이름 인공 약 높다 감기 대중 인위 짜다 막걸리 대접 볼 관심 타 남다 기회 하이 볼 섞다 향기 도주 집들이 독하다 이름 파티 어떻다 워낙 보기 마치다 가미 다기 수고 맛잇을걱닡아 모으다 햡 담날 대박 물맛 안되다 읺았어 짜다 빠져들다 소비 안나 이색 보리 빨랏 부족하다 화이팅 편 감홍 쇼핑 대다 도자기 생신 술맛 지다 높다 개봉 준비 깊다 볼 외국 아버님 조명 이벤트 용이 얼 눈 신분 보기 작다 내기 불빛 사은 비주 즐겁다 준비 생신 아깝다 주신 싸다 품 아버님 비쥬 조명도 반응 켜다 고맙다 동학 저렴하다 청 서비스 술잔 소주 강쇠주 오메 기술 조선 대비 요리 사용 데우다 조사 쓰다 감사 음식 알콜 경험 청주 강쇠 가성 전주 모주 뜨다 신기하다 화주 좋아하다 주문 예쁘다 이쁘다 얼음 산 토닉 워터 빨대 깨지다 빙 탄복 박스 약하다 국산 오프너 위트 소백산 제공 분위기 아내 크리스마스 마음 마루 베베 솔직하다 초보자 와이프 작성 위트 디자인 굳다 달다 시큼하다 달달 선물 깔끔하다 뒤 비비 이 있 하 것 들 그 되 수 이 보 않 없 나 사람 주 아니 등 같 우리 때 년 가 한 지 대하 오 말 일 그렇 위하 기한 달라 첫날 첨 주말 걱정 전이 이유 해보다 저번 보지 함 기대다 상 비 베스트 도수 음 존맛 개인'.split()
                 ) #불용어 추가
stopwords=set(stopwords) # 중복제거    

# 형태소 분석 함수 만들기
def okt_pos_tagging2(string):
    pos_words = okt.pos(string, stem=True, norm=True) # 형태소 분석. 단어는 사전형으로 바꿔주기
    words = [word for word, tag in pos_words if tag 
             in ['Noun', 'Adjective', 'Verb','Adverb'] if word not in stopwords ]

    # n_gram 만들기
    egram = list(everygrams(words, min_len=1, max_len=1))
    egram_token = [' '.join(grams) for grams in egram]

    return egram_token

def okt_pos_tagging(string):
    pos_words = okt.pos(string, stem=True, norm=True) # 형태소 분석. 단어는 사전형으로 바꿔주기
    words = [word for word, tag in pos_words if tag 
             in ['Noun', 'Adjective', 'Verb','Adverb'] if word not in stopwords ]

    return words


In [4]:
# 불러올 csv 이름 리스트
# 전체 리뷰를 불러온후 tf-idf 분석
# name_list =["막걸리_복순도가","막걸리_느린마을","막걸리_죽향도가"]
# name_list =["금이산농원_복숭아와인","덕유양조_산머루주","배상면주가_빙탄복","산내들_소백산스위트와인","컨츄리와인_영동포도와인"]
# name_list =["청주_고헌정_동학1957_특선","청주_양촌양조_무농약_우렁이쌀","청주_오메기맑은술","청주_우포의아침","탁주_모주","탁주_이화주"]
# name_list =["증류주_감홍로_40도","증류주_금설_35도","증류주_더한매실원주_13도","증류주_도원결의_15도","증류주_도원결의_25도","증류주_도원결의_40도"
#             ,"증류주_박재서명인_안동소주_22도","증류주_박재서명인_안동소주_35도","증류주_박재서명인_안동소주_45도","증류주_서울의밤_17도","증류주_서울의밤_25도"
#             ,"증류주_안동소주_일품_21도","증류주_안동소주_일품_40도"]
name_list =["막걸리_복순도가","막걸리_느린마을","막걸리_죽향도가"
            ,"과실주_금이산농원_복숭아와인","과실주_덕유양조_산머루주","과실주_배상면주가_빙탄복","과실주_산내들_소백산스위트와인","과실주_컨츄리와인_영동포도와인"
            ,"청주_고헌정_동학1957_특선","청주_양촌양조_무농약_우렁이쌀","청주_오메기맑은술","청주_우포의아침","탁주_모주","탁주_이화주"
            ,"증류주_감홍로_40도","증류주_금설_35도","증류주_더한매실원주_13도","증류주_도원결의_15도","증류주_도원결의_25도","증류주_도원결의_40도"
            ,"증류주_박재서명인_안동소주_22도","증류주_박재서명인_안동소주_35도","증류주_박재서명인_안동소주_45도","증류주_서울의밤_17도","증류주_서울의밤_25도"
            ,"증류주_안동소주_일품_21도","증류주_안동소주_일품_40도"]

all_data = pd.DataFrame()

for name in name_list:
    try: 
        data = pd.read_csv(f"{name}.csv", encoding='utf-8-sig')
    except:
        data = pd.read_csv(f"{name}.csv", encoding='cp949')
    # 전처리
    data.drop_duplicates(['text'],ignore_index=True, inplace=True) # 중복 제거
    try:
        data.columns = ['date', 'star','doc']
    except:
        data.columns = ['date', 'star','doc','name']
    data.doc = data.doc.str.replace("[^가-힣 ]"," ") # 한글만 남기고 특수문자, 숫자, 영어 삭제
    data.doc = data.doc.str.replace("\s+", " ") # white space 삭제
    data.doc = data.doc.str.replace("럽고목","럽고 목")
    data.doc = data.doc.str.replace("부 드럽","부드럽")
    data.doc = data.doc.str.replace("가성", "가성비")
    data.doc = data.doc.str.replace("더락", "언더락")
    data.dropna(inplace=True)
    data.reset_index(drop=True, inplace=True)
    # globals()["감홍로 40도"] 등으로 데이터 프레임 저장됨
    globals()[f"{name}"] = data
    all_data = pd.concat([all_data,data],axis=0)


C:\Users\user\AppData\Local\Temp\ipykernel_18316\3721083391.py:29: FutureWarning: The default value of regex will change from True to False in a future version.
  data.doc = data.doc.str.replace("[^가-힣 ]"," ") # 한글만 남기고 특수문자, 숫자, 영어 삭제
C:\Users\user\AppData\Local\Temp\ipykernel_18316\3721083391.py:30: FutureWarning: The default value of regex will change from True to False in a future version.
  data.doc = data.doc.str.replace("\s+", " ") # white space 삭제
C:\Users\user\AppData\Local\Temp\ipykernel_18316\3721083391.py:29: FutureWarning: The default value of regex will change from True to False in a future version.
  data.doc = data.doc.str.replace("[^가-힣 ]"," ") # 한글만 남기고 특수문자, 숫자, 영어 삭제
C:\Users\user\AppData\Local\Temp\ipykernel_18316\3721083391.py:30: FutureWarning: The default value of regex will change from True to False in a future version.
  data.doc = data.doc.str.replace("\s+", " ") # white space 삭제
C:\Users\user\AppData\Local\Temp\ipykernel_18316\3721083391.py:29: FutureWarning

In [5]:
all_data

date  star                                                doc name
0     2022-10-31     5  지인으로부터 알게된 복순도가 막걸리처음 먹는순간 너무 맛있어서 깜짝놀랐어요원래 술을...  NaN
1     2022-11-17     5  그냥 차게 마셔도 군내나 잔여물 찌꺼기 느낌이 거의 없이 깔끔담백하고 샴페인처럼 톡...  NaN
2     2022-10-19     5  지인이 비싼데 고급지고 맛있는 막걸리가있다고 해서하도 궁금하여 한번 시켜봤어요배송도...  NaN
3     2022-10-28     3  본인은 맛있었는데 아버지는 너무 삭힌거같다는 평이네요 새콤함이 좀 있긴함근데 막걸리...  NaN
4     2022-10-13     5  복순도가 맛있다고 한참전에 소문만 들었지 먹어본것은 올해가 처음이네요 평소에도 달달...  NaN
...          ...   ...                                                ...  ...
3703  2021-05-11     5                                도수에비해 부드러운 목넘김과 맛있음  NaN
3704  2021-04-26     5                                    선물했는데 아주 좋아해줬어요  NaN
3705  2021-03-18     5    포장보고 사진을 안찍을수가 없네요 완벽해요 원래 마시던 거라 싸게잘샀습니다 많이파세용  NaN
3706  2021-04-09     5                                     매번 만족합니다 번창하세요  NaN
3707  2021-04-05     5                          포장이 완전 튼튼합니다 술맛은 남편이좋아했어요  NaN

[114493 rows x 4 columns]

In [6]:
all_data.name.unique()

array([nan, '천년주가 전주모주', '술샘 이화주 8도'], dtype=object)

In [7]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer(tokenizer=okt_pos_tagging)
tfidf_fit = tfidf.fit(all_data.doc)

c:\Users\user\AppData\Local\Programs\Python\Python38\lib\site-packages\sklearn\feature_extraction\text.py:524: UserWarning: The parameter 'token_pattern' will not be used since 'tokenizer' is not None'
  warnings.warn(


In [8]:
# 특징을 추출할 문서의 tf-idf를 구함
# "막걸리_복순도가" : 110,"막걸리_느린마을" : 130,"막걸리_죽향도가" : 300
a = "막걸리_복순도가"
bow_rep_tfidf = tfidf_fit.transform(globals()[a].doc)
word_count = pd.DataFrame({
    '단어': tfidf.get_feature_names(),
    'tf-idf': bow_rep_tfidf.sum(axis=0).flat,
    'idf': tfidf.idf_
})

c:\Users\user\AppData\Local\Programs\Python\Python38\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


In [9]:
# idf 가 높을수록 잘 안나오는 단어
# tf-idf 가 높을수록 중요한 단어
# 두값을 적절히 조정해서 특징 추출

word_count.sort_values('tf-idf',ascending=False).head(50)[word_count['idf']>4.5][word_count['tf-idf'] * (len(all_data)/len(globals()[a]))>200]

C:\Users\user\AppData\Local\Temp\ipykernel_18316\3115847107.py:5: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  word_count.sort_values('tf-idf',ascending=False).head(50)[word_count['idf']>4.5][word_count['tf-idf'] * (len(all_data)/len(globals()[a]))>200]


단어      tf-idf       idf
7387     샴페인  315.528522  6.149996
8239    스파클링  150.733406  5.963666
10036     와인  140.380114  4.798564
8477      신맛  135.253240  6.656813
7270      상큼  116.666255  6.584492
13132    청량감  105.266007  7.083757
776    고급스럽다   92.770606  5.646122
2924    달콤하다   88.401926  5.704190
2839      단맛   78.956364  5.515780
10175   요구르트   74.555510  7.477794
12684    진하다   66.674172  6.018914
7091      산미   65.491509  7.197239
7030     사이다   63.995164  7.171814
13146   청량하다   60.445858  7.637642
14397     평소   51.988679  6.563778
7783       손   50.009775  7.455321
12622      진   48.901308  6.985317
11206      입   48.478547  6.427688
9764      열다   48.186481  7.114888
2650      늘다   45.457608  6.185248
3165      덕분   45.426480  6.816395
7532      설명   45.346460  7.147019
10714    음료수   45.083053  6.742916
6968      사랑   45.039130  7.227743
9349     어머니   44.928172  7.335072
13574     캠핑   44.569348  7.091450
1999     나누다   44.446719  6.964698
5433       뭐   43.542108  6.586821
5069      명품   42.800607  7.706635
7293     새롭다   41.361201  7.099202
12390     중독   40.449387  7.282302
7790      손님   40.254614  6.934545
13694    콤달콤   40.145168  8.217461
7628      세번   39.532069  7.171814
15021     행사   39.352354  7.773080
14156   특이하다   38.932397  7.277640
5778      발효   38.417684  7.180218
1638      기존   37.011231  7.512479
14628   필요없다   36.983064  7.263783
7311    색다르다   36.794925  7.406531
3340    독특하다   36.369640  7.444271
13308     추가   36.232808  6.873726

In [10]:
a1 =["증류주_감홍로_40도","증류주_금설_35도","증류주_더한매실원주_13도","증류주_도원결의_15도","증류주_도원결의_25도","증류주_도원결의_40도"
            ,"증류주_박재서명인_안동소주_22도","증류주_박재서명인_안동소주_35도","증류주_박재서명인_안동소주_45도","증류주_서울의밤_17도","증류주_서울의밤_25도"
            ,"증류주_안동소주_일품_21도","증류주_안동소주_일품_40도"]
Tags1 = {"gamhonglo": [],"geumsul": [],"masil": [],"dowon15": [],"dowon25": [],"dowon40": [],"andong22": [],"andong35": [],"andong45": []
        ,"seoul17": [],"seoul25": [],"ilpum21": [],"ilpum40": []}
keys1 = ["gamhonglo","geumsul","masil","dowon15","dowon25","dowon40","andong22","andong35","andong45","seoul17","seoul25","ilpum21","ilpum40"]
for i in range(len(a1)):
    bow_rep_tfidf = tfidf_fit.transform(globals()[a1[i]].doc)
    word_count = pd.DataFrame({
        '단어': tfidf.get_feature_names(),
        'tf-idf': bow_rep_tfidf.sum(axis=0).flat,
        'idf': tfidf.idf_
    })
    
    df1 = word_count.sort_values('tf-idf',ascending=False).head(50)[word_count['idf']>4.5][word_count['tf-idf'] * (len(all_data)/len(globals()[a1[i]]))>200]
    df1.to_csv(f'증류주_특징{i}.csv',encoding='utf-8-sig')

    # for i in range(len(Tags)):
    for j in df1['단어']:
        Tags1[keys1[i]].append(j)
Tags1['gamhonglo']

c:\Users\user\AppData\Local\Programs\Python\Python38\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)
C:\Users\user\AppData\Local\Temp\ipykernel_18316\3306238777.py:15: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df1 = word_count.sort_values('tf-idf',ascending=False).head(50)[word_count['idf']>4.5][word_count['tf-idf'] * (len(all_data)/len(globals()[a1[i]]))>200]


['계피',
 '고급스럽다',
 '명주',
 '위스키',
 '약주',
 '약초',
 '술병',
 '점',
 '따로',
 '물건',
 '매력',
 '아주아주',
 '은은하다',
 '다행',
 '애',
 '독특하다',
 '조만간',
 '양',
 '평',
 '용기',
 '상자',
 '추가',
 '종이',
 '늦다',
 '명불허전',
 '확인',
 '특이하다',
 '양가',
 '직접',
 '자체',
 '손님',
 '종이가방',
 '아끼다',
 '판매',
 '으뜸',
 '신경',
 '내용물',
 '나중',
 '세트',
 '예술',
 '늘다',
 '진하다',
 '음미']

In [11]:
a2 = ["청주_고헌정_동학1957_특선","청주_양촌양조_무농약_우렁이쌀","청주_오메기맑은술","청주_우포의아침"]
Tags2 = {"donghak": [],"yangchon": [],"omegi": [],"upo": []}
keys2 = ["donghak","yangchon","omegi","upo"]

for i in range(len(a2)):
    bow_rep_tfidf = tfidf_fit.transform(globals()[a2[i]].doc)
    word_count = pd.DataFrame({
        '단어': tfidf.get_feature_names(),
        'tf-idf': bow_rep_tfidf.sum(axis=0).flat,
        'idf': tfidf.idf_
    })
    
    df2 = word_count.sort_values('tf-idf',ascending=False).head(50)[word_count['idf']>4.5][word_count['tf-idf'] * (len(all_data)/len(globals()[a2[i]]))>50]
    df2.to_csv(f'청주_모주_특징{i}.csv',encoding='utf-8-sig')

    # for i in range(len(Tags)):
    for j in df2['단어']:
        Tags2[keys2[i]].append(j)
Tags2['donghak']

C:\Users\user\AppData\Local\Temp\ipykernel_18316\4046132186.py:13: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df2 = word_count.sort_values('tf-idf',ascending=False).head(50)[word_count['idf']>4.5][word_count['tf-idf'] * (len(all_data)/len(globals()[a2[i]]))>50]


['사케',
 '단맛',
 '약주',
 '은은하다',
 '순하다',
 '매력',
 '누룩',
 '깨끗하다',
 '깔다',
 '훌륭하다',
 '리용',
 '고급스럽다',
 '정종',
 '먼저',
 '고르다',
 '접',
 '안주',
 '생기다',
 '쟁',
 '평소',
 '해산물',
 '추가',
 '쌀',
 '평범하다',
 '드라이',
 '차갑다',
 '반주',
 '캠핑',
 '미리',
 '남기다',
 '갑',
 '만해',
 '혼술',
 '새롭다',
 '습',
 '늘다',
 '산미',
 '완벽하다',
 '아부지',
 '조만간',
 '든든하다',
 '부드러움',
 '덜하다']

In [12]:
# 특징을 추출할 문서의 tf-idf를 구함
a3 = ["막걸리_복순도가","막걸리_느린마을","막걸리_죽향도가","탁주_모주","탁주_이화주"]
Tags3 = {"boksundoga": [],"maeul": [],"jukhyang": [],"moju": [],"ihwa": []}
keys3 = ["boksundoga","maeul","jukhyang","moju","ihwa"]

for i in range(len(a3)):
    bow_rep_tfidf = tfidf_fit.transform(globals()[a3[i]].doc)
    word_count = pd.DataFrame({
        '단어': tfidf.get_feature_names(),
        'tf-idf': bow_rep_tfidf.sum(axis=0).flat,
        'idf': tfidf.idf_
    })
    
    df3 = word_count.sort_values('tf-idf',ascending=False).head(50)[word_count['idf']>4.5][word_count['tf-idf'] * (len(all_data)/len(globals()[a3[i]]))>110]
    df3.to_csv(f'막걸리_특징{i}.csv',encoding='utf-8-sig')

    # for i in range(len(Tags)):
    for j in df3['단어']:
        Tags3[keys3[i]].append(j)
Tags3['boksundoga']

C:\Users\user\AppData\Local\Temp\ipykernel_18316\806687868.py:14: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df3 = word_count.sort_values('tf-idf',ascending=False).head(50)[word_count['idf']>4.5][word_count['tf-idf'] * (len(all_data)/len(globals()[a3[i]]))>110]


['샴페인',
 '스파클링',
 '와인',
 '신맛',
 '상큼',
 '청량감',
 '고급스럽다',
 '달콤하다',
 '단맛',
 '요구르트',
 '진하다',
 '산미',
 '사이다',
 '청량하다',
 '평소',
 '손',
 '진',
 '입',
 '열다',
 '늘다',
 '덕분',
 '설명',
 '음료수',
 '사랑',
 '어머니',
 '캠핑',
 '나누다',
 '뭐',
 '명품',
 '새롭다',
 '중독',
 '손님',
 '콤달콤',
 '세번',
 '행사',
 '특이하다',
 '발효',
 '기존',
 '필요없다',
 '색다르다',
 '독특하다',
 '추가']

In [13]:
a4 = ["과실주_금이산농원_복숭아와인","과실주_덕유양조_산머루주","과실주_배상면주가_빙탄복","과실주_산내들_소백산스위트와인","과실주_컨츄리와인_영동포도와인"]
Tags4 = {"nongwon": [],"duckyang": [],"baesang": [],"sobak": [],"yungdong": []}
keys4 = ["nongwon","duckyang","baesang","sobak","yungdong"]

for i in range(len(a4)):
    bow_rep_tfidf = tfidf_fit.transform(globals()[a4[i]].doc)
    word_count = pd.DataFrame({
        '단어': tfidf.get_feature_names(),
        'tf-idf': bow_rep_tfidf.sum(axis=0).flat,
        'idf': tfidf.idf_
    })
    
    df4 = word_count.sort_values('tf-idf',ascending=False).head(50)[word_count['idf']>4.5][word_count['tf-idf'] * (len(all_data)/len(globals()[a4[i]]))>110]
    df4.to_csv(f'과실주_특징{i}.csv',encoding='utf-8-sig')

    # for i in range(len(Tags)):
    for j in df4['단어']:
        Tags4[keys4[i]].append(j)
Tags4['nongwon']

C:\Users\user\AppData\Local\Temp\ipykernel_18316\2840894832.py:13: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df4 = word_count.sort_values('tf-idf',ascending=False).head(50)[word_count['idf']>4.5][word_count['tf-idf'] * (len(all_data)/len(globals()[a4[i]]))>110]


['복숭아',
 '와인',
 '달콤하다',
 '은은하다',
 '차갑다',
 '여자친구',
 '사과',
 '디저트',
 '기념일',
 '단맛',
 '진하다',
 '화이트와인',
 '상큼',
 '과일',
 '뽁뽁이',
 '그렇게',
 '나중',
 '사이즈',
 '탄산수',
 '드라이',
 '용량',
 '미리',
 '놀다',
 '여행가',
 '갈다',
 '올라오다',
 '품절',
 '직접',
 '대요',
 '의향',
 '줄',
 '탱',
 '나오다',
 '코르크',
 '서다',
 '화이트',
 '덕분',
 '감동',
 '이산',
 '덜',
 '음료수',
 '스티로폼',
 '뜯다']

In [14]:
mak_df0 = pd.read_csv('막걸리_특징0.csv')
del mak_df0['Unnamed: 0']
mak_df1 = pd.read_csv('막걸리_특징1.csv')
del mak_df1['Unnamed: 0']
mak_df2 = pd.read_csv('막걸리_특징2.csv')
del mak_df2['Unnamed: 0']
mak_df3 = pd.read_csv('막걸리_특징3.csv')
del mak_df3['Unnamed: 0']
mak_df4 = pd.read_csv('막걸리_특징4.csv')
del mak_df4['Unnamed: 0']
mak_df0

단어      tf-idf       idf
0     샴페인  315.528522  6.149996
1    스파클링  150.733406  5.963666
2      와인  140.380114  4.798564
3      신맛  135.253240  6.656813
4      상큼  116.666255  6.584492
5     청량감  105.266007  7.083757
6   고급스럽다   92.770606  5.646122
7    달콤하다   88.401926  5.704190
8      단맛   78.956364  5.515780
9    요구르트   74.555510  7.477794
10    진하다   66.674172  6.018914
11     산미   65.491509  7.197239
12    사이다   63.995164  7.171814
13   청량하다   60.445858  7.637642
14     평소   51.988679  6.563778
15      손   50.009775  7.455321
16      진   48.901308  6.985317
17      입   48.478547  6.427688
18     열다   48.186481  7.114888
19     늘다   45.457608  6.185248
20     덕분   45.426480  6.816395
21     설명   45.346460  7.147019
22    음료수   45.083053  6.742916
23     사랑   45.039130  7.227743
24    어머니   44.928172  7.335072
25     캠핑   44.569348  7.091450
26    나누다   44.446719  6.964698
27      뭐   43.542108  6.586821
28     명품   42.800607  7.706635
29    새롭다   41.361201  7.099202
30     중독   40.449387  7.282302
31     손님   40.254614  6.934545
32    콤달콤   40.145168  8.217461
33     세번   39.532069  7.171814
34     행사   39.352354  7.773080
35   특이하다   38.932397  7.277640
36     발효   38.417684  7.180218
37     기존   37.011231  7.512479
38   필요없다   36.983064  7.263783
39   색다르다   36.794925  7.406531
40   독특하다   36.369640  7.444271
41     추가   36.232808  6.873726

In [15]:
gwa_df0 = pd.read_csv('과실주_특징0.csv')
del gwa_df0['Unnamed: 0']
gwa_df1 = pd.read_csv('과실주_특징1.csv')
del gwa_df1['Unnamed: 0']
gwa_df2 = pd.read_csv('과실주_특징2.csv')
del gwa_df2['Unnamed: 0']
gwa_df3 = pd.read_csv('과실주_특징3.csv')
del gwa_df3['Unnamed: 0']
gwa_df4 = pd.read_csv('과실주_특징4.csv')
del gwa_df4['Unnamed: 0']
gwa_df0

단어      tf-idf       idf
0     복숭아  279.695629  5.555704
1      와인  195.814443  4.798564
2    달콤하다   30.246868  5.704190
3    은은하다   29.349902  6.169768
4     차갑다   23.654974  7.630998
5    여자친구   21.656840  7.765476
6      사과   21.622068  8.278830
7     디저트   21.316801  8.043108
8     기념일   20.844635  8.053158
9      단맛   16.918922  5.515780
10    진하다   16.685492  6.018914
11  화이트와인   16.460205  7.984839
12     상큼   13.557121  6.584492
13     과일   13.409691  7.031507
14    뽁뽁이   13.383344  8.083930
15    그렇게   11.139843  7.592032
16     나중   11.093262  7.197239
17    사이즈   10.530240  7.852487
18    탄산수   10.426515  7.277640
19    드라이   10.134626  7.780743
20     용량    9.709574  7.254650
21     미리    9.555217  7.042476
22     놀다    9.513866  7.433342
23    여행가    9.353768  8.073567
24     갈다    9.260557  6.889376
25   올라오다    9.130570  6.773347
26     품절    9.052148  8.137418
27     직접    8.394219  6.773347
28     대요    8.373039  7.210198
29     의향    8.291960  7.637642
30      줄    8.229541  7.002831
31      탱    8.186490  7.611325
32    나오다    8.132456  6.692440
33    코르크    8.116926  8.841615
34     서다    8.075899  6.651826
35    화이트    7.929579  8.677986
36     덕분    7.916959  6.816395
37     감동    7.886523  7.126817
38     이산    7.865601  9.757906
39      덜    7.861739  7.027877
40    음료수    7.816195  6.742916
41   스티로폼    7.725717  7.268380
42     뜯다    7.618134  7.483492

In [16]:
chung_df0 = pd.read_csv('청주_모주_특징0.csv')
del chung_df0['Unnamed: 0']
chung_df1 = pd.read_csv('청주_모주_특징1.csv')
del chung_df1['Unnamed: 0']
chung_df2 = pd.read_csv('청주_모주_특징2.csv')
del chung_df2['Unnamed: 0']
chung_df3 = pd.read_csv('청주_모주_특징3.csv')
del chung_df3['Unnamed: 0']
chung_df0

단어     tf-idf       idf
0      사케  17.114705  7.860786
1      단맛   6.964913  5.515780
2      약주   6.799959  8.159641
3    은은하다   6.648447  6.169768
4     순하다   6.326251  6.527980
5      매력   6.301339  7.017066
6      누룩   5.642637  7.401254
7    깨끗하다   5.091343  7.180218
8      깔다   5.073559  6.978397
9    훌륭하다   5.066302  6.992286
10     리용   4.946351  9.875689
11  고급스럽다   4.378679  5.646122
12     정종   3.981566  8.229437
13     먼저   3.944246  7.757929
14    고르다   3.915875  7.827996
15      접   3.852843  7.245600
16     안주   3.835931  6.547959
17    생기다   3.754377  7.236632
18      쟁   3.752894  7.554527
19     평소   3.555992  6.563778
20    해산물   3.501348  8.716452
21     추가   3.484756  6.873726
22      쌀   3.399198  7.494986
23   평범하다   3.171954  8.063310
24    드라이   3.132688  7.780743
25    차갑다   3.115574  7.630998
26     반주   3.076556  7.250115
27     캠핑   3.029663  7.091450
28     미리   3.013826  7.042476
29    남기다   2.955538  7.560681
30      갑   2.902392  8.677986
31     만해   2.855056  7.713804
32     혼술   2.828336  7.263783
33    새롭다   2.815978  7.099202
34      습   2.716243  7.167639
35     늘다   2.706858  6.185248
36     산미   2.698707  7.197239
37   완벽하다   2.681049  6.924693
38    아부지   2.656868  7.664671
39    조만간   2.653864  7.438792
40   든든하다   2.643858  8.605226
41   부드러움   2.642294  7.401254
42    덜하다   2.597508  7.296420

In [17]:
# a : 리스트
for i in range(len(a)):
    globals()['df{}'.format(i)] = pd.read_csv(f'증류주_특징{i}.csv')
    del globals()['df{}'.format(i)]['Unnamed: 0']

# a = []
# for i in range(len(keys)):
#     a.append('df'+str(i))
#     a[i] = pd.read_csv(f'증류주_특징{i}.csv')
#     del a[i]['Unnamed: 0']

# a[0]

In [18]:
df2

단어      tf-idf       idf
0     매실주  198.569190  6.671927
1      매실  184.928398  6.349328
2     매화수   42.077268  8.126489
3     진하다   20.878445  6.018914
4      단맛   20.255335  5.515780
5    달콤하다   20.142131  5.704190
6    은은하다   18.912496  6.169768
7       꿀   16.867046  6.867534
8       곳   12.784486  6.710741
9      상큼   12.021531  6.584492
10    탄산수   11.473035  7.277640
11    음료수   11.163155  6.742916
12    순하다   10.801393  6.527980
13     꿀맛   10.376256  7.354973
14     식당   10.354058  7.375278
15     음료   10.039922  6.870625
16     서다   10.026310  6.651826
17    마싯다    9.337216  7.773080
18     판매    9.109087  6.737481
19     덕분    8.992049  6.816395
20     비교    8.834271  7.038806
21      입    8.796758  6.427688
22      살    8.694218  7.272999
23     매다    8.550903  8.073567
24   굉장하다    8.496675  6.724022
25     금방    8.454521  6.864453
26     쓸다    8.216279  7.110943
27     손님    8.092389  6.934545
28     안주    8.060659  6.547959
29     반주    7.961069  7.250115
30     꿀향    7.896763  8.489395
31     늘다    7.875631  6.185248
32     여러    7.848404  7.530284
33     혼술    7.776046  7.263783
34     캠핑    7.508317  7.091450
35  고급스럽다    7.375657  5.646122
36     냄새    7.345750  6.751124
37   완벽하다    7.200071  6.924693
38    설중매    7.187766  9.875689
39     늦다    7.104727  6.889376
40      덜    7.017806  7.027877
41      짱    7.016233  7.006371
42      액    6.982349  8.819636

In [19]:
def getHashTagString(list_of_tags):
	hashTagString = ""

	for tag in list_of_tags:
		hashTagString += " #" + tag

	return hashTagString

In [20]:
print(getHashTagString(Tags1['gamhonglo'][0:3])[:].strip())
print(getHashTagString(Tags1['geumsul'][0:3])[:].strip())
print(getHashTagString(Tags1['masil'][0:3])[:].strip())
print(getHashTagString(Tags1['dowon15'][0:3])[:].strip())
print(getHashTagString(Tags1['dowon25'][0:3])[:].strip())
print(getHashTagString(Tags1['dowon40'][0:3])[:].strip())
print(getHashTagString(Tags1['andong22'][0:3])[:].strip())
print(getHashTagString(Tags1['andong35'][0:3])[:].strip())
print(getHashTagString(Tags1['andong45'][0:3])[:].strip())
print(getHashTagString(Tags1['seoul17'][0:3])[:].strip())
print(getHashTagString(Tags1['seoul25'][0:3])[:].strip())
print(getHashTagString(Tags1['ilpum21'][0:3])[:].strip())
print(getHashTagString(Tags1['ilpum40'][0:3])[:].strip())

#계피 #고급스럽다 #명주
#금가루 #젤리 #금
#매실주 #매실 #매화수
#복숭아 #은은하다 #단맛
#복숭아 #은은하다 #시럽
#복숭아 #은은하다 #칵테일
#희다 #정종 #완벽하다
#누룩 #희다 #서명
#고급스럽다 #상자 #분도
#은은하다 #매실 #레몬
#매실 #은은하다 #레몬
#은은하다 #깔다 #뒷맛
#위스키 #깨끗하다 #완벽하다


In [21]:
print(getHashTagString(Tags2['donghak'][0:3])[:].strip())
print(getHashTagString(Tags2['yangchon'][0:3])[:].strip())
print(getHashTagString(Tags2['omegi'][0:3])[:].strip())
print(getHashTagString(Tags2['upo'][0:3])[:].strip())

#사케 #단맛 #약주
#약주 #백세주 #완벽하다
#제주도 #와인 #화이트와인
#사케 #드라이 #단맛


In [22]:
print(getHashTagString(Tags4['nongwon'][0:3])[:].strip())
print(getHashTagString(Tags4['duckyang'][0:3])[:].strip())
print(getHashTagString(Tags4['baesang'][0:3])[:].strip())
print(getHashTagString(Tags4['sobak'][0:3])[:].strip())
print(getHashTagString(Tags4['yungdong'][0:3])[:].strip())

#복숭아 #와인 #달콤하다
#머루 #와인 #진하다
#스파클링 #복분자 #와인
#와인 #달콤하다 #포도
#와인 #달콤하다 #포도


In [23]:
print(getHashTagString(Tags3['boksundoga'][0:3])[:].strip())
print(getHashTagString(Tags3['maeul'][0:3])[:].strip())
print(getHashTagString(Tags3['jukhyang'][0:3])[:].strip())
print(getHashTagString(Tags3['moju'][0:3])[:].strip())
print(getHashTagString(Tags3['ihwa'][0:3])[:].strip())

#샴페인 #스파클링 #와인
#우유 #단맛 #순하다
#꿀 #단맛 #꿀맛
#음료 #음료수 #진하다
#요거트 #특이하다 #과일


In [24]:
df = pd.read_csv('전통주(종합).csv', encoding='utf-8-sig')
del df['Unnamed: 0']
del df['비고']
df = df.dropna()
df = df.reset_index(drop=True)
df

이름              해시태그   종류                          양조장 위치  \
0                  감홍로    #계피 #고급스럽다 #명주   청주           경기도 파주시 파주읍 윗가마울길 149   
1                   금설       #금가루 #젤리 #금   청주           경기도 파주시 파주읍 윗가마울길 149   
2             도원결의 15도    #복숭아 #은은하다 #단맛  증류주           경북 영덕군 강구면 소월1길 16-10   
3             도원결의 25도    #복숭아 #은은하다 #시럽  증류주           경북 영덕군 강구면 소월1길 16-10   
4             도원결의 40도   #복숭아 #은은하다 #칵테일  증류주           경북 영덕군 강구면 소월1길 16-10   
5       박재서명인 안동소주 22도     #희다 #정종 #완벽하다  증류주             경북 안동시 풍산읍 산업단지6길 6   
6       박재서명인 안동소주 35도       #누룩 #희다 #서명  증류주             경북 안동시 풍산읍 산업단지6길 6   
7       박재서명인 안동소주 45도    #고급스럽다 #상자 #분도  증류주             경북 안동시 풍산읍 산업단지6길 6   
8             서울의밤 25도     #매실 #은은하다 #레몬  증류주             서울시 은평구 증산로7길 28-13   
9          안동소주 일품 21도     #은은하다 #깔다 #뒷맛  증류주           경상북도 안동시 풍산읍 ㈜ 안동소주일품   
10         안동소주 일품 40도  #위스키 #깨끗하다 #완벽하다  증류주           경상북도 안동시 풍산읍 ㈜ 안동소주일품   
11  고헌정 동학 1957 특선 13도       #사케 #단맛 #약주  증류주            충청북도 충주시 산척면 샛강영길 39   
12       양촌양조 무농약 우렁이쌀    #약주 #백세주 #완벽하다   청주   충청남도 논산시 양촌면 매죽헌로 1665번길 14-7   
13             오메기 맑은술   #제주도 #와인 #화이트와인   청주         제주특별자치도 제주시 애월읍 애원로 283   
14               우포의아침      #사케 #드라이 #단맛   청주           경남 창녕군 대지면 대지농공단지길 40   
15                복순도가    #샴페인 #스파클링 #와인  막걸리           울산광역시 울주군 상북면 향산동길 50   
16      배상면주가 느린마을 막걸리      #우유 #단맛 #순하다  막걸리  서울특별시 서초구 강남대로 27길 7-9 우곡빌딩 6층   
17                죽향도가        #꿀 #단맛 #꿀맛  막걸리             전라남도 담양군 담양읍 삼다리 78   
18                  모주     #음료 #음료수 #진하다   탁주             전북 남원시 주천면 장백산로 130   
19        금이산농원 복숭아 와인    #복숭아 #와인 #달콤하다  과실주            세종특별자치시 전의면 가느실길 127   
20           덕유양조 산머루주      #머루 #와인 #진하다  과실주         전라북도 무주군 안성면 장무로 1375-7   
21           배상면주가 빙탄복    #스파클링 #복분자 #와인  과실주  서울특별시 서초구 강남대로 27길 7-9 우곡빌딩 6층   
22      산내들 소백산 스위트 와인     #와인 #달콤하다 #포도  과실주          경상북도 영주시 단산면 좌석리 277-1   

      도수      용량       가격     평점  \
0   40.0   400.0  45000.0    4.8   
1   35.0   375.0  35000.0    4.9   
2   15.0   360.0   5500.0    4.8   
3   25.0   360.0   6310.0    4.8   
4   40.0   360.0  10930.0    4.8   
5   22.0   360.0   5000.0   4.85   
6   35.0   360.0   7500.0   4.85   
7   45.0   800.0  38000.0   4.83   
8   25.0   375.0   7110.0   4.84   
9   21.0   350.0   5280.0   4.84   
10  40.0   350.0   8590.0   4.86   
11  13.0   375.0   3500.0   4.84   
12  14.0   500.0  16000.0   4.86   
13  16.0   500.0  30000.0   4.83   
14  14.0   700.0   4500.0    4.7   
15   6.5   935.0  12000.0    4.8   
16   6.0  1000.0  10000.0    4.8   
17   6.0   600.0   3800.0    4.8   
18   1.0   500.0   3000.0   4.69   
19  12.0   500.0  20000.0  4..82   
20  16.0   350.0   5700.0   4.79   
21   7.0   370.0   4000.0    4.8   
22  12.0   750.0  15500.0   4.76   

                                                    맛                 향  \
0                                 깔끔 은은 위스키 부드러움 호불호             계피 한약재   
1                                  부드러움 진함 강함 구수함 깔끔함                인삼   
2                                            상큼 은은 단맛               복숭아   
3                                            상큼 은은 단맛               복숭아   
4                                            상큼 은은 단맛               복숭아   
5                                         깔끔 깨끗 부드러움                 누룩   
6                                       세다 깔끔 깨끗 부드러움                누룩   
7                                       세다 깔끔 깨끗 부드러움                누룩   
8                                       부드러움 깔끔 단맛 강함            매실 자두    
9                                     부드러움 깔끔함 은은함 순함               곡물향   
10                                      깔끔함 단맛 은은함 순함               곡물향   
11                        단맛 가볍다 은은하다 부드럽다 달달 사케 드라이                누룩향   
12                             가볍다 반주 달달 단맛 부드럽다 순하다       약초향 고구마향 약재    
13                   깔끔하다 달콤하다 은은하다 부드럽다 달달 산미 맑다 상큼      과일 화이트 와인 과실    
14                                 부드러움 청주 드라이 달달 도수             누룩향 미미   
15  산뜻하다 스

In [25]:
# dtype 변환
df['도수'] = pd.to_numeric(df['도수'])

In [26]:
df.dtypes

이름         object
해시태그       object
종류         object
양조장 위치     object
도수        float64
용량        float64
가격        float64
평점         object
맛          object
향          object
리뷰 수      float64
dtype: object

In [27]:
# 과일향(복숭아, 포도, 머루, 매실)
# 새콤한(상큼, 요거트)
# 고소한(우유, 누룩, 막걸리)
# 달콤한(꿀향, 꿀, 단맛, 달달, 달콤하다)
# 쌉싸름한(계피, 인삼)
# 깔끔한(순하다)
# 부드러운(부드럽다, 은은하다)
# 진한(걸쭉한, 진하다)
# 가벼운(가볍다)
# 탄산있는(탄산, 스파클링)
# 분위기있는(와인, 고급스럽다, 샴페인)
# 도수낮은(10도 이하)
# 도수높은(10도 이상)

In [28]:
fruit = ['복숭아', '포도', '머루', '매실','레몬','복분자']
acidulous = ['상큼', '요거트']
savory = ['우유', '누룩', '막걸리']
sweet = ['꿀향','꿀맛', '꿀', '단맛', '달달', '달콤하다','젤리','시럽','칵테일','음료수']
bitter = ['계피', '인삼','약주']
clean = ['희다','위스키','깔끔','깔끔하다','사케','깨끗하다']
soft = ['부드럽다', '은은하다']
thick = ['걸쭉한', '진하다']
light = ['가볍다','순하다','샴페인']
dry = ['드라이']
sparkling = ['탄산', '스파클링']
mood = ['와인', '고급스럽다', '명주','금','금가루']
low_alcohol = [df.loc[df['도수']<=10]]
high_alcohol = [df.loc[df['도수']>10]]
# ['fruit','acidulous','savory','sweet','bitter','clean','soft','thick','light','sparkling','mood','low_alcohol','high_alcohol']
# ['복숭아', '포도', '머루', '매실','상큼', '요거트','우유', '누룩', '막걸리','꿀향', '꿀', '단맛', '달달', '달콤하다','계피', '인삼','순하다','부드럽다', '은은하다','걸쭉한', '진하다','가볍다','탄산', '스파클링','와인', '고급스럽다', '샴페인']

In [29]:
df2 = pd.DataFrame(columns=['fruit','acidulous','savory','sweet','bitter','clean','soft','thick','light','sparkling','mood','low_alcohol_level'])
df3 = pd.concat([df.iloc[:,:3],df['맛'],df['향'],df2], axis=1)
df3.head(3)

이름            해시태그   종류                    맛       향 fruit acidulous  \
0       감홍로  #계피 #고급스럽다 #명주   청주  깔끔 은은 위스키 부드러움 호불호   계피 한약재   NaN       NaN   
1        금설     #금가루 #젤리 #금   청주   부드러움 진함 강함 구수함 깔끔함      인삼   NaN       NaN   
2  도원결의 15도  #복숭아 #은은하다 #단맛  증류주             상큼 은은 단맛     복숭아   NaN       NaN   

  savory sweet bitter clean soft thick light sparkling mood low_alcohol_level  
0    NaN   NaN    NaN   NaN  NaN   NaN   NaN       NaN  NaN               NaN  
1    NaN   NaN    NaN   NaN  NaN   NaN   NaN       NaN  NaN               NaN  
2    NaN   NaN    NaN   NaN  NaN   NaN   NaN       NaN  NaN               NaN

In [30]:
# list_hashtag = [fruit,acidulous,savory,sweet,bitter,clean,soft,thick,light,sparkling,mood]
df3.해시태그 = df3.해시태그.str.replace("#","")
for i in range(len(df3.이름)):
    for j in df3.해시태그[i].split():
        if(j in fruit):
            df3.fruit[i] = j
        elif(j in acidulous):
            df3.acidulous[i] = j
        elif(j in savory):
            df3.savory[i] = j
        elif(j in sweet):
            df3.sweet[i] = j
        elif(j in bitter):
            df3.bitter[i] = j
        elif(j in clean):
            df3.clean[i] = j
        elif(j in soft):
            df3.soft[i] = j
        elif(j in thick):
            df3.thick[i] = j
        elif(j in light):
            df3.light[i] = j
        elif(j in sparkling):
            df3.sparkling[i] = j
        elif(j in mood):
            df3.mood[i] = j
        else:
            pass

    if(df['도수'][i]<=10):
        df3.low_alcohol_level[i] = 0
    else:
        df3.low_alcohol_level[i] = 1
df3

이름           해시태그   종류  \
0                  감홍로    계피 고급스럽다 명주   청주   
1                   금설       금가루 젤리 금   청주   
2             도원결의 15도    복숭아 은은하다 단맛  증류주   
3             도원결의 25도    복숭아 은은하다 시럽  증류주   
4             도원결의 40도   복숭아 은은하다 칵테일  증류주   
5       박재서명인 안동소주 22도     희다 정종 완벽하다  증류주   
6       박재서명인 안동소주 35도       누룩 희다 서명  증류주   
7       박재서명인 안동소주 45도    고급스럽다 상자 분도  증류주   
8             서울의밤 25도     매실 은은하다 레몬  증류주   
9          안동소주 일품 21도     은은하다 깔다 뒷맛  증류주   
10         안동소주 일품 40도  위스키 깨끗하다 완벽하다  증류주   
11  고헌정 동학 1957 특선 13도       사케 단맛 약주  증류주   
12       양촌양조 무농약 우렁이쌀    약주 백세주 완벽하다   청주   
13             오메기 맑은술   제주도 와인 화이트와인   청주   
14               우포의아침      사케 드라이 단맛   청주   
15                복순도가    샴페인 스파클링 와인  막걸리   
16      배상면주가 느린마을 막걸리      우유 단맛 순하다  막걸리   
17                죽향도가        꿀 단맛 꿀맛  막걸리   
18                  모주     음료 음료수 진하다   탁주   
19        금이산농원 복숭아 와인    복숭아 와인 달콤하다  과실주   
20           덕유양조 산머루주      머루 와인 진하다  과실주   
21           배상면주가 빙탄복    스파클링 복분자 와인  과실주   
22      산내들 소백산 스위트 와인     와인 달콤하다 포도  과실주   

                                                    맛                 향 fruit  \
0                                 깔끔 은은 위스키 부드러움 호불호             계피 한약재   NaN   
1                                  부드러움 진함 강함 구수함 깔끔함                인삼   NaN   
2                                            상큼 은은 단맛               복숭아   복숭아   
3                                            상큼 은은 단맛               복숭아   복숭아   
4                                            상큼 은은 단맛               복숭아   복숭아   
5                                         깔끔 깨끗 부드러움                 누룩   NaN   
6                                       세다 깔끔 깨끗 부드러움                누룩   NaN   
7                                       세다 깔끔 깨끗 부드러움                누룩   NaN   
8                                       부드러움 깔끔 단맛 강함            매실 자두     레몬   
9                                     부드러움 깔끔함 은은함 순함               곡물향   NaN   
10                                      깔끔함 단맛 은은함 순함               곡물향   NaN   
11                        단맛 가볍다 은은하다 부드럽다 달달 사케 드라이                누룩향   NaN   
12                             가볍다 반주 달달 단맛 부드럽다 순하다       약초향 고구마향 약재    NaN   
13                   깔끔하다 달콤하다 은은하다 부드럽다 달달 산미 맑다 상큼      과일 화이트 와인 과실    NaN   
14                                 부드러움 청주 드라이 달달 도수             누룩향 미미   NaN   
15  산뜻하다 스파클링 탄산 꿀떡꿀떡 순하다 달짝지근하다 달달 부드럽다 고소하다 청량하다...  청포도 누룩 포도 복숭아 향기   NaN   
16  고소하다 뽀얗다 담백하다 크림 우유 부드럽다 달맛 달다 달짝지근하다 달달하다 고급스...     사과 요구르트 곡물 과일   NaN   
17  부드럽다 순하다 굉장하다 깔끔하다 달콤하다 달달 중독 청량하다 텁텁 긍정 라이트 맑...                꿀향   NaN   
18                                              단맛 순함                계피   NaN   
19                                 달달하다 신맛 깔끔하다 자연스러움   복숭아향 약함 은은하게 퍼짐   복숭아   
20                                        단맛 달달하다 달다             머루향 진함    머루   
21                              탄산음료같다 도수가높지않다 뒷맛이 깔끔               복분자   복분자   
22                                          부드러움 목넘김               향긋하다    포도   

   acidulous savory sweet bitter clean  soft thick light sparkling   mood  \
0        NaN    NaN   NaN     계피   NaN   NaN   NaN   NaN       NaN     명주   
1        NaN    NaN    젤리    NaN   NaN   NaN   NaN   NaN       NaN      금   
2        NaN    NaN    단맛    NaN   NaN  은은하다   NaN   NaN       NaN    NaN   
3        NaN    NaN    시럽    NaN   NaN  은은하다   NaN   NaN       NaN    NaN   
4        NaN    NaN   칵테일    NaN   NaN  은은하다   NaN   NaN       NaN    NaN   
5        NaN    NaN   NaN    NaN    희다   NaN   NaN   NaN       NaN    NaN   
6        NaN     누룩   NaN    NaN    희다   NaN   NaN   NaN       NaN    NaN   
7        NaN    NaN   NaN    NaN   NaN   NaN   NaN   NaN       NaN  고급스럽다   
8        NaN    NaN   NaN    NaN   NaN  은은하다   NaN   NaN       NaN    NaN   
9        NaN    NaN   NaN    NaN   NaN  은은하다   NaN   NaN       NaN    NaN   
10       NaN    NaN   NaN    NaN  깨끗하다   NaN   NaN   NaN       NaN    NaN   
11       NaN    NaN    단맛     약주    사케   NaN  

In [31]:
# 원핫인코딩
# pd.get_dummies(df2['해시태그 항목'])

In [32]:
# def recommend(Dataframe):
#     for i in Dataframe:
#         for j in range(len(df['해시태그'])):
#             a = df['해시태그'][j].split()
#             if(a.__contains__('#'+i)):
#                 return df['이름']
#             else:
#                 pass
# recommend(df2['해시태그 항목'])

In [33]:
# 원핫인코딩 입력
# for i in df2.columns:
#     for j in range(len(df3.해시태그)):
#         if(('#'+str(i)) in df3.해시태그[j].split()):
#             df3[i][j] = 1
#         else:
#             df3[i][j] = 0

# 해시태그 항목 라벨링
# b = df3.해시태그.unique()
# for i in range(len(b)):
#        b[i] = b[i].replace("#","")
#        b[i] = b[i].split()
# b = sum(b,[])
# b = list(set(b))

# df3['해시태그_vector'] = df3['해시태그'].str.replace("#","")

# for index, value in enumerate(b):
#     df3['해시태그_vector'] = df3['해시태그_vector'].str.replace(value, str(index))
# for i in range(len(df3['해시태그_vector'])):
#     df3['해시태그_vector'][i] = df3['해시태그_vector'][i].split()
#     df3['해시태그_vector'][i] = list(map(int, df3['해시태그_vector'][i]))
#     # df3['해시태그_vector'][i] = pd.to_numeric(df3['해시태그_vector'][i])
# df3['해시태그_vector']

In [34]:
# df3['원핫인코딩'] = 0
# for i in range(len(df3['이름'])):
#     df3['원핫인코딩'][i] = df3.iloc[i,11:-2].values
# df3

In [35]:
# df3['fruit'] = df3['복숭아'] + df3['포도'] + df3['머루'] + df3['매실']
# df3['acidulous'] = df3['상큼'] + df3['요거트']
# df3['savory'] = df3['우유'] + df3['누룩'] +  df3['막걸리']
# df3['sweet'] = df3['꿀향'] + df3['꿀'] + df3['단맛'] +  df3['달달'] + df3['달콤하다']
# df3['bitter'] = df3['계피'] + df3['인삼']
# df3['clean'] = df3['순하다']
# df3['soft'] = df3['부드럽다'] + df3['은은하다']
# df3['thick'] = df3['걸쭉한'] + df3['진하다']
# df3['light'] = df3['가볍다']
# df3['sparkling'] = df3['탄산'] + df3['스파클링']
# df3['mood'] = df3['와인'] + df3['고급스럽다'] + df3['샴페인']
# df3.drop(['복숭아', '포도', '머루', '매실','상큼', '요거트','우유', '누룩', '막걸리','꿀향', '꿀', '단맛', '달달', '달콤하다','계피', '인삼','순하다','부드럽다', '은은하다','걸쭉한', '진하다','가볍다','탄산', '스파클링','와인', '고급스럽다', '샴페인'], axis=1, inplace=True)
# df3.head(3)

In [36]:
# df3.to_csv('DB종합.csv',encoding='utf-8-sig')

In [37]:
# df3.to_csv('DB종합2.csv',encoding='utf-8-sig')    # 카테고리 정리

### 로지스틱 회귀

In [38]:
from sklearn.model_selection import train_test_split  

train_features, test_features, train_labels, test_labels = train_test_split(df3[:19], df3[19:])

ValueError: Found input variables with inconsistent numbers of samples: [19, 4]

In [ ]:
from sklearn.preprocessing import StandardScaler  
  
scaler = StandardScaler()  
  
train_features = scaler.fit_transform(train_features)
test_features = scaler.transform(test_features)

In [ ]:
from sklearn.linear_model import LogisticRegression  
  
model = LogisticRegression()  
model.fit(train_features, train_labels)

In [ ]:
print(model.score(train_features, train_labels))

In [ ]:
print(model.score(test_features, test_labels))

### 결정트리

In [ ]:
from sklearn.tree import DecisionTreeClassifier
from sklearn import tree
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.tree import export_graphviz
from subprocess import check_call
from sklearn.preprocessing import LabelEncoder
from IPython.display import Image
import pydotplus 
import os

In [ ]:
encoder = LabelEncoder()
a = ['fruit','acidulous','savory','sweet','bitter','clean','soft','thick','light','sparkling','mood','low_alcohol_level']
for i in range(len(a)):
    x_encoded = encoder.fit_transform(df3[a[i]])
    print(x_encoded)
print(encoder.classes_)
# y 데이터에만 존재하는 새로 출현한 데이터를 신규 클래스로 추가한다 (중요!!!)
# for label in np.unique(y):
#     if label not in encoder.classes_:
#         encoder.classes_ = np.append(encoder.classes_, label) #미처리 시 ValueError발생
# y_encoded = encoder.transform(y)

[5 5 3 3 3 5 5 5 0 5 5 5 5 5 5 5 5 5 5 3 1 2 4]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[2 2 2 2 2 2 0 2 2 2 2 2 2 2 2 2 1 2 2 2 2 2 2]
[7 5 1 3 6 7 7 7 7 7 7 1 7 7 1 7 1 0 4 2 7 7 2]
[0 2 2 2 2 2 2 2 2 2 2 1 1 2 2 2 2 2 2 2 2 2 2]
[3 3 3 3 3 2 2 3 3 3 0 1 3 3 1 3 3 3 3 3 3 3 3]
[1 1 0 0 0 1 1 1 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1]
[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 0 1 1]
[2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 0 1 2 2 2 2 2 2]
[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 0 1]
[2 1 4 4 4 4 4 0 4 4 4 4 4 3 4 3 4 4 4 3 3 3 3]
[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 1 1 0 1]
[0 1]


In [ ]:
encoder.inverse_transform(x_encoded)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0,
       1], dtype=object)

In [ ]:
tree_model = DecisionTreeClassifier(max_depth=3)
tree_model.fit(x,y)

NameError: name 'x' is not defined

In [ ]:
export_graphviz(
    tree_model, # 학습한 모형
    out_file = './alcohol_tree_model.dot', # .dot 파일 저장 위치
    feature_names = df3.feature_names[2:], # 사용한 변수 이름
    class_names = df3.target_names, # 예측할 타겟 클래스 이름
    rounded=True, # 사각형 끝을 둥글게
    filled=True # 사각형 안 색깔 채우기
)

In [ ]:
check_call(['dot','-Tpng','alcohol_tree_model.dot','-o','OutputFile.png'])

### 오토인코더