In [1]:
import numpy as np

In [2]:
# 1차원
list = [1,2,3,4,5]
arr = np.array(list)
arr

array([1, 2, 3, 4, 5])

In [3]:
arr1 = np.array([1,2,3,4,5])
arr1

array([1, 2, 3, 4, 5])

In [4]:
arr2 = np.array([[1,2,3],[5,4,3]])
arr2

array([[1, 2, 3],
       [5, 4, 3]])

In [37]:
arr3 = np.array([[[1,2,2,6],[6,1,3,4]],[[3,4,5,4],[1,5,3,5]],[[1,3,5,6],[3,6,3,3]]])
arr3

array([[[1, 2, 2, 6],
        [6, 1, 3, 4]],

       [[3, 4, 5, 4],
        [1, 5, 3, 5]],

       [[1, 3, 5, 6],
        [3, 6, 3, 3]]])

In [6]:
arr.shape

(5,)

In [31]:
arr1.shape

(5,)

In [35]:
arr2.shape

(2, 3)

In [38]:
arr3.shape

(3, 2, 4)

In [39]:
print(arr.size)
print(arr2.size)
print(arr3.size)

5
6
24


In [40]:
print(arr.dtype)
print(arr2.dtype)
print(arr3.dtype)

int32
int32
int32


In [41]:
# 차원(Dimension) 확인
print(arr.ndim)
print(arr2.ndim)
print(arr3.ndim)

1
2
3


#### 차원이 많아지면 코드 작성 어떻게 함??
    다차원은 보통 직접 입력하지 않고 엑셀 파일 받아서 바로 작성



In [45]:
arr4 = np.array([[[[1,2],[2,6]],[[6,1],[3,4]]],[[[1,2],[2,6]],[[6,1],[3,4]]],[[[1,3],[5,6]],[[3,6],[3,3]]]])
arr4

array([[[[1, 2],
         [2, 6]],

        [[6, 1],
         [3, 4]]],


       [[[1, 2],
         [2, 6]],

        [[6, 1],
         [3, 4]]],


       [[[1, 3],
         [5, 6]],

        [[3, 6],
         [3, 3]]]])

In [46]:
print(arr4.shape)
print(arr4.size)
print(arr4.dtype)
print(arr4.ndim)

(3, 2, 2, 2)
24
int32
4
