In [2]:
import numpy as np

In [2]:
# 1차원
list = [1,2,3,4,5]
arr = np.array(list)
arr

array([1, 2, 3, 4, 5])

In [3]:
arr1 = np.array([1,2,3,4,5])
arr1

array([1, 2, 3, 4, 5])

In [4]:
arr2 = np.array([[1,2,3],[5,4,3]])
arr2

array([[1, 2, 3],
       [5, 4, 3]])

In [37]:
arr3 = np.array([[[1,2,2,6],[6,1,3,4]],[[3,4,5,4],[1,5,3,5]],[[1,3,5,6],[3,6,3,3]]])
arr3

array([[[1, 2, 2, 6],
        [6, 1, 3, 4]],

       [[3, 4, 5, 4],
        [1, 5, 3, 5]],

       [[1, 3, 5, 6],
        [3, 6, 3, 3]]])

In [6]:
# 배열 크기
arr.shape

(5,)

In [31]:
arr1.shape

(5,)

In [35]:
arr2.shape

(2, 3)

In [38]:
arr3.shape

(3, 2, 4)

In [39]:
# 전체 요소 개수
print(arr.size)
print(arr2.size)
print(arr3.size)

5
6
24


In [40]:
print(arr.dtype)
print(arr2.dtype)
print(arr3.dtype)

int32
int32
int32


In [41]:
# 차원(Dimension) 확인
print(arr.ndim)
print(arr2.ndim)
print(arr3.ndim)

1
2
3


#### 차원이 많아지면 코드 작성 어떻게 함??
    다차원은 보통 직접 입력하지 않고 엑셀 파일 받아서 바로 작성



In [45]:
arr4 = np.array([[[[1,2],[2,6]],[[6,1],[3,4]]],[[[1,2],[2,6]],[[6,1],[3,4]]],[[[1,3],[5,6]],[[3,6],[3,3]]]])
arr4

array([[[[1, 2],
         [2, 6]],

        [[6, 1],
         [3, 4]]],


       [[[1, 2],
         [2, 6]],

        [[6, 1],
         [3, 4]]],


       [[[1, 3],
         [5, 6]],

        [[3, 6],
         [3, 3]]]])

In [46]:
print(arr4.shape)
print(arr4.size)
print(arr4.dtype)
print(arr4.ndim)

(3, 2, 2, 2)
24
int32
4


In [73]:
# 모든 값 0 배열 생성하기
arr_zeros = np.zeros((3,4),dtype=int)   # 실수로 만들어지기 때문에 정수로 변환하고 싶을 때
arr_zeros

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [71]:
# 모든 값 0 배열 생성하기
arr_zeros = np.zeros((3,4))
arr_zeros.dtype = int   
arr_zeros

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0]])

In [69]:
# 모든 값 1 배열 생성하기
arr_ones = np.ones((3,4),dtype=int)
arr_ones

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [70]:
# 모든 값 1 배열 생성하기
arr_ones = np.ones((3,4))
arr_ones.dtype = int
arr_ones

array([[         0, 1072693248,          0, 1072693248,          0,
        1072693248,          0, 1072693248],
       [         0, 1072693248,          0, 1072693248,          0,
        1072693248,          0, 1072693248],
       [         0, 1072693248,          0, 1072693248,          0,
        1072693248,          0, 1072693248]])

In [59]:
# 특정 값으로 배열 생성하기
arr_full = np.full((7,7),7)
arr_full

array([[7, 7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7, 7]])

In [64]:
list = []
for i in range(51):
    list.append(i)
arr = np.array(list)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [72]:
arr1 = np.arange(1,51)  # for문 range와 같음
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [3]:
arr1 = np.array(range(50))
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [79]:
arr1 = np.arange(1,51,7)
arr1

array([ 1,  8, 15, 22, 29, 36, 43, 50])

In [82]:
# 랜덤 값 배열 생성
# 0~1 사이의 난수를 임의로 뽑음
arr = np.random.rand(2,3)
arr

array([[0.21460124, 0.37758291, 0.51627166],
       [0.26547995, 0.60779478, 0.06142736]])

In [83]:
# 2~10 사이 숫자 1개 임의의 뽑음
arr = np.random.randint(2,10)
arr

3

In [89]:
# 2~10 사이 숫자 여러개 임의의 뽑음 -> 행렬로 만들어 줌
arr = np.random.randint(2,10,(5,7))
arr

array([[2, 2, 2, 5, 5, 5, 9],
       [3, 6, 8, 9, 7, 9, 9],
       [7, 3, 8, 2, 3, 5, 3],
       [9, 7, 2, 9, 5, 5, 6],
       [3, 2, 7, 8, 6, 7, 7]])

In [91]:
# 원하는 타입 지정하여 배열 생성
arr_type = np.array([1.2,2.2,3.2], dtype = np.int64)
arr_type

array([1, 2, 3], dtype=int64)

In [92]:
# 타입 변경
arr_type = arr_type.astype("float64")
arr_type

array([1., 2., 3.])

In [93]:
arr_type.dtype

dtype('float64')

In [118]:
arr_a = np.array([1,2,3])
arr_b = np.array([4,5,6])
arr_a * arr_b

array([ 4, 10, 18])

In [124]:
arr_a * 5

array([ 5, 10, 15])

#### indexing & slicing

In [139]:
arr_1 = np.array([[1,2,3],[4,5,6]])
arr_1[1][-1]

6

In [134]:
arr_1[1,0]

4

In [138]:
arr_1[1]

array([4, 5, 6])

In [148]:
arr1 = np.arange(10)
arr1[2:5] = 77
arr1

array([ 0,  1, 77, 77, 77,  5,  6,  7,  8,  9])

In [149]:
# 2차원 array 생성
arr2 = np.arange(50).reshape(5,10)
arr2

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [150]:
arr2[:2,:]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [157]:
arr2[:,:1]

array([[ 0],
       [10],
       [20],
       [30],
       [40]])

In [158]:
arr2[:,0]

array([ 0, 10, 20, 30, 40])

In [159]:
arr2[:4,:5]

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24],
       [30, 31, 32, 33, 34]])

In [166]:
arr2[4,-2], arr2[2,-1], arr2[1,2]

(48, 29, 12)

#### boolean 색인
    True인 값들만 추출

In [170]:
score = np.array([80,75,55,96,30])
score[score >= 80]

array([80, 96])

In [178]:
name = np.array(['영화','동원','성우','수민'])
bol = np.array([False, True, False, True])
name[bol]


array(['동원', '수민'], dtype='<U2')

In [179]:
name == "운비"

array([False, False, False, False])

In [186]:
score = np.array([[60,60],[70,70],[80,80],[90,90]])
score[name == '동원']

array([[70, 70]])

#### universally function
    numpy 안에 있는 함수

In [194]:
arr = np.random.randint(1, 10, (2,5))
print(arr)
print(sum(arr)) # 같은 위치의 요소들 합
print(arr.sum())
print(np.sum(arr))
print(arr.mean())

[[8 2 4 9 4]
 [7 4 9 6 2]]
[15  6 13 15  6]
55
55
5.5


In [200]:
# 루트
arr = np.arange(1,6)
print(np.sqrt(arr))

[1.         1.41421356 1.73205081 2.         2.23606798]


In [201]:
# 절대값
arr = np.array([-1,2,-5,7,-8])
np.abs(arr)

array([1, 2, 5, 7, 8])