In [83]:
import numpy as np
import random
from random import randint

In [5]:
arr = np.zeros(10, dtype = int)
arr[4] = 1
arr

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0])

In [9]:
arr1 = np.arange(10,50)
arr1

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [13]:
arr1 = np.arange(9).reshape((3,3))
arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [18]:
arr_rd = np.random.randint(1,10,(3,3,3))
arr_rd

array([[[9, 1, 6],
        [4, 8, 3],
        [6, 3, 5]],

       [[8, 4, 6],
        [6, 7, 6],
        [6, 2, 9]],

       [[8, 7, 5],
        [5, 4, 4],
        [8, 4, 1]]])

In [19]:
arr_rd = np.random.random((3,3,3))
arr_rd

array([[[0.36139858, 0.49907066, 0.84447329],
        [0.42536488, 0.79843032, 0.14642588],
        [0.513928  , 0.92011386, 0.22183866]],

       [[0.54762039, 0.923484  , 0.81903218],
        [0.61819017, 0.69601593, 0.76786324],
        [0.68352582, 0.03117159, 0.53208507]],

       [[0.24150894, 0.04664233, 0.76130015],
        [0.97693814, 0.43622523, 0.1892005 ],
        [0.59832362, 0.11198228, 0.58416159]]])

In [26]:
arr_rd = np.random.random(30)
print(arr_rd)
print(arr_rd.size)
print(np.mean(arr_rd))

[0.54128418 0.48718522 0.52527123 0.3980821  0.11595281 0.55882432
 0.13400104 0.37187418 0.53323881 0.29539288 0.09157335 0.063711
 0.64669131 0.06550846 0.11453051 0.28507188 0.15104115 0.320316
 0.73296454 0.76450688 0.01061986 0.42380696 0.25787591 0.77315103
 0.92141685 0.63159217 0.57210637 0.25331101 0.3609603  0.2282042 ]
30
0.38766888323406046


In [29]:
mid_score = [10,20,30]
final_score = [40,50,60]
total_score = []
for i in range(len(mid_score)):
    total_score.append(mid_score[i] + final_score[i])
total_score

[50, 70, 90]

In [34]:
mid_score = np.array([10,20,30])
final_score = np.array([40,50,60])
total_score = mid_score + final_score
print("시험성적 합계 :",total_score)

시험성적 합계 : [50 70 90]


In [37]:
print("시험성적 합계 :",total_score / 2)

시험성적 합계 : [25. 35. 45.]


In [50]:
array_a = np.arange(10)
array_b = np.array(range(10))
array_c = np.arange(0,10,2)
array_a, array_b, array_c

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([0, 2, 4, 6, 8]))

In [53]:
print(array_c.shape)
print(array_c.ndim)
print(array_c.dtype)
print(array_c.size)

(5,)
1
int32
5


In [54]:
# 배열 원소 크기(byte 단위)
# 8bit = 1byte
array_c.itemsize

4

In [57]:
salary = np.array([220,250,240])
salary * 2

array([440, 500, 480])

In [81]:
players = [[170,70],[180,80],[190,90],[200,100]]
np_players = np.array(players)
print("몸무게가 80이상인 선수의 정보 : \n", np_players[np_players[:,1] >= 80])
print("키가 180이상인 선수의 정보 : \n", np_players[np_players[:,0] >= 180])
# 인덱싱은 1개, 슬라이싱은 여러개 가져오는건데 슬라이싱은 하나의 []안에 작성해야 됨

몸무게가 80이상인 선수의 정보 : 
 [[180  80]
 [190  90]
 [200 100]]
키가 180이상인 선수의 정보 : 
 [[180  80]
 [190  90]
 [200 100]]


In [116]:
revenue_in_yen = np.random.randint(1,10,(30)) * 10000
revenue_in_yen

array([20000, 70000, 30000, 90000, 40000, 70000, 90000, 80000, 40000,
       30000, 70000, 70000, 50000, 70000, 70000, 40000, 50000, 40000,
       60000, 30000, 60000, 10000, 10000, 20000, 90000, 40000, 10000,
       60000, 80000, 40000])

In [117]:
won_array = revenue_in_yen * 9.70
won_array.astype("int64")

array([194000, 679000, 291000, 872999, 388000, 679000, 872999, 776000,
       388000, 291000, 679000, 679000, 484999, 679000, 679000, 388000,
       484999, 388000, 582000, 291000, 582000,  97000,  97000, 194000,
       872999, 388000,  97000, 582000, 776000, 388000], dtype=int64)

In [128]:
low_won_array = won_array[won_array <= 500000]
print(low_won_array)
print(low_won_array.size)

[194000. 291000. 388000. 388000. 291000. 485000. 388000. 485000. 388000.
 291000.  97000.  97000. 194000. 388000.  97000. 388000.]
16


In [118]:
dolar_array = won_array * 0.00072
dolar_array.astype("int64")

array([139, 488, 209, 628, 279, 488, 628, 558, 279, 209, 488, 488, 349,
       488, 488, 279, 349, 279, 419, 209, 419,  69,  69, 139, 628, 279,
        69, 419, 558, 279], dtype=int64)

In [119]:
print("연봉 : %d엔"%np.sum(revenue_in_yen))
print("연봉 : %d달러"%np.sum(dolar_array))

연봉 : 1530000엔
연봉 : 10685달러
