K-fold

In [103]:
import numpy as np 
import pandas as pd 
from sklearn.model_selection import KFold

x_data = np.array([
    [2,1],
    [3,2],
    [3,4],
    [5,5],
    [7,5],
    [2,5],
    [8,9],
    [9,10],
    [6, 12],
    [9,2],
    [6,10],
    [2,4]
])

In [104]:
kf = KFold(n_splits=5)
for train_indwx, test_index in kf.split(x_data):
    print(train_indwx)
    print(test_index)
    print("")

[ 3  4  5  6  7  8  9 10 11]
[0 1 2]

[ 0  1  2  6  7  8  9 10 11]
[3 4 5]

[ 0  1  2  3  4  5  8  9 10 11]
[6 7]

[ 0  1  2  3  4  5  6  7 10 11]
[8 9]

[0 1 2 3 4 5 6 7 8 9]
[10 11]



K-Fold 교차검즘 -> 보통 회귀 문제에서 사용됨
- 학습 데이터와 테스트 데이터를 k개의 세트로 나누어 검증하는 방법 
- 데이터셋이 굉장히 적을 때 훈련데이터를 어떻게든 최대한 늘려보려고 사용되기도 하는 방법 
- 여러 개의 훈련 테스트 짝으로 검증과정을 거침

라이브러리의 종류
- kf = KFold(n_splits=5)
    - for문을 이용해야하고 코드가 길어짐

    < 아래 두개는 비슷해보이지만 출력의 형태가 다르다. >
- cv_result = cross_validate(model, x_data, y_data)
- cv_score = cross_val_score(model, x_data, y_data, cv=5)

5-7. 모델링(모델선택, 학습, 평가)

k-fold

In [105]:
from sklearn.linear_model import LinearRegression
Ir = LinearRegression()

x_data = np.array([
    [2,1],
    [3,2],
    [3,4],
    [5,5],
    [7,5],
    [2,5],
    [8,9],
    [9,10],
    [6, 12],
    [9,2],
    [6,10],
    [2,4]
])
y_data = np.array([3,5,7,10,12,7,13,13,12,13,12,6])

train_scores = [] 
test_scores = []

kf = KFold(n_splits=5)

for train_index, test_index in kf.split(x_data): #5번 검증
    x_train = np.array(x_data)[train_index] 
    y_train = np.array(y_data) [train_index] 
    x_test = np.array(x_data)[test_index] 
    y_test = np.array(y_data)[test_index]

    model_kf = LinearRegression()
    model_kf.fit(x_train, y_train)

    score = model_kf.score(x_train, y_train) 
    train_scores.append(score)

    score = model_kf.score(x_test, y_test) 
    test_scores. append(score)


In [106]:
print(train_scores,"\n", test_scores)
# 각각의 데이터셋의 정확도가 아래와 같이 나오는 것을 알 수 있다.

[0.9522707858769932, 0.9469593697441799, 0.9446524178499608, 0.9232432525564045, 0.9166499001004778] 
 [-1.1475590101753324, 0.56847222331606, 0.0, -11.7747639790487, 0.9602035173350366]


In [107]:
print(np.array(train_scores).mean(), np.array(test_scores).mean())

0.9367551452256032 -2.278729449714587


cross-validation

In [108]:
from sklearn.model_selection import cross_validate

In [120]:
model = LinearRegression()

# cross 교차를 사용한 방법에 대한 정확도 평균
cv_result = cross_validate(model, x_data, y_data)
print(cv_result['test_score'].mean())
print(cv_result)


0.5348810553622219
{'fit_time': array([0.        , 0.00100517, 0.        , 0.        , 0.        ]), 'score_time': array([0.        , 0.        , 0.        , 0.        , 0.00151658]), 'test_score': array([0.        , 0.77653085, 0.        , 0.97679893, 0.9210755 ])}


In [110]:
df = pd.DataFrame(cv_result)
df = df.sort_values(by='test_score', ascending = False)
df

fit_time  score_time  test_score
4  0.000000       0.000    0.960204
1  0.000000       0.001    0.568472
2  0.000000       0.000    0.000000
0  0.000991       0.000   -1.147559
3  0.001010       0.000  -11.774764

cross_val_score

In [111]:
from sklearn.model_selection import cross_val_score

In [121]:
model = LinearRegression()
model.fit(x_data, y_data)
cv_score = cross_val_score(model, x_data, y_data, cv=5)
print('cv mean score : ', cv_score.mean())
print(cv_score)

cv mean score :  0.5348810553622219
[0.         0.77653085 0.         0.97679893 0.9210755 ]


##### 분류

 분류문제에서는 범주형 값의 편향된 분산을 막기 위해  
 범주형의 비율에 따라 나눠준다.

 이것을 '계층적 K-Fold'라고 한다

In [117]:
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split

In [116]:
x_data = np.array([
    [2,1],
    [3,2],
    [3,4],
    [5,5],
    [7,5],
    [2,5],
    [8,9],
    [9,10],
    [6, 12],
    [9,2],
    [6,10],
    [2,4]
])
y_data = np.array([2,2,2,1,1,2,0,0,0,1,0,2])
labels = ['a', 'b', 'c']

In [123]:
model = LogisticRegression()
cv_result = cross_val_score(model, x_data, y_data)
print(cv_result.mean(), "\n", cv_result)

0.9333333333333332 
 [0.66666667 1.         1.         1.         1.        ]


c:\Users\user\anaconda3\lib\site-packages\sklearn\model_selection\_split.py:676: UserWarning: The least populated class in y has only 3 members, which is less than n_splits=5.
  warnings.warn(


In [124]:
model = LinearRegression()

# cross 교차를 사용한 방법에 대한 정확도 평균
cv_result = cross_validate(model, x_data, y_data)
print(cv_result['test_score'].mean(), "\n", cv_result)

df = pd.DataFrame(cv_result)
df = df.sort_values(by='test_score', ascending = False)
df


0.5348810553622219 
 {'fit_time': array([0.00099683, 0.00099635, 0.        , 0.        , 0.        ]), 'score_time': array([0.        , 0.        , 0.        , 0.00100684, 0.        ]), 'test_score': array([0.        , 0.77653085, 0.        , 0.97679893, 0.9210755 ])}


fit_time  score_time  test_score
3  0.000000    0.001007    0.976799
4  0.000000    0.000000    0.921075
1  0.000996    0.000000    0.776531
0  0.000997    0.000000    0.000000
2  0.000000    0.000000    0.000000

계층적 k겹 교차검증(Stratified k-fold cross validation)
- 분류 모델에 적용 
- k-겹 교차검증 모델은 k-fold가 원본 데이터 집합의 레이블 분포를 학습 및 검증데이터 세트에
제대로 분배하지 못하는 문제를 해결해줌 
- target값(정답) 레이블/클래스의 속성값의 개수를 골고루 넣어주게 됨


In [127]:
from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import accuracy_score
from sklearn.datasets import load_iris

In [129]:
iris = load_iris()
x = iris['data']
y = iris['target']

In [137]:
model = LogisticRegression()
skf = StratifiedKFold(n_splits=5, random_state=42, shuffle=True)

idx_iter = 0
cv_accuracy = []

for train_index, test_index in skf.split(x,y):
    # print(x, y)
    x_train, x_test = x[train_index], x[test_index]
    y_train, y_test = y[train_index], y[test_index]
    
    model.fit(x_train, y_train)
    pred = model.predict(x_test)
    
    idx_iter += 1
    accuracy = np.round(accuracy_score(y_test, pred), 4)
    
    train_size = x_train.shape[0]
    test_size = x_test.shape[0]
    
    print(f'{idx_iter}번째 교차 검증 정확도 : {accuracy} \n 학습 데이터 크기 : {train_size} \n 검증 데이터 크기 : {test_size} \n')
    cv_accuracy.append(accuracy)

1번째 교차 검증 정확도 : 1.0 
 학습 데이터 크기 : 120 
 검증 데이터 크기 : 30 

2번째 교차 검증 정확도 : 0.9667 
 학습 데이터 크기 : 120 
 검증 데이터 크기 : 30 

3번째 교차 검증 정확도 : 0.9333 
 학습 데이터 크기 : 120 
 검증 데이터 크기 : 30 

4번째 교차 검증 정확도 : 1.0 
 학습 데이터 크기 : 120 
 검증 데이터 크기 : 30 

5번째 교차 검증 정확도 : 0.9333 
 학습 데이터 크기 : 120 
 검증 데이터 크기 : 30 



c:\Users\user\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
c:\Users\user\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i 