In [15]:
import warnings
warnings.filterwarnings('ignore')

In [31]:
import pandas as pd
import numpy as np
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import GridSearchCV
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier

In [17]:
iris = load_iris()
x = iris.data
y = iris.target

In [22]:
scaler = StandardScaler()
x_scaled = scaler.fit_transform(x)

In [26]:
# x_train, x_test, y_train, y_test = train_test_split(x, y, random_state=0)

# scaler = StandardScaler()
# scaler.fit(x_train)
# x_train_scaled = scaler.transform(x_train)
# x_test_scaled = scaler.transform(x_test)

# scaler = StandardScaler()
# scaler.fit_transform(x_train)
# scaler.transform(x_test)

In [38]:
x_train, x_test, y_train, y_test = train_test_split(x_scaled, y, random_state=0)

In [39]:
len(x_train), len(y_train)

(112, 112)

In [68]:
param_knn = {'n_neighbors':range(1,10)}
knn = GridSearchCV(KNeighborsClassifier(), param_knn, cv=5)
knn.fit(x_train, y_train)   
# x_scaled를 넣지 않는 이유 : score를 할 때 새로운 data로 뽑아야 되는데 전체 data를 넣게 되면 이미 학습한 data이기 때문

GridSearchCV(cv=5, estimator=KNeighborsClassifier(),
             param_grid={'n_neighbors': range(1, 10)})

In [41]:
print('최적의 parameter : ', knn.best_params_)
print('최고 교차 검증 점수 : ', knn.best_score_)    # x_train에 대한 R2
print('최고 성능 모델 : ', knn.best_estimator_)
print('최적의 index : ', knn.best_index_)

최적의 parameter :  {'n_neighbors': 6}
최고 교차 검증 점수 :  0.9666666666666668
최고 성능 모델 :  KNeighborsClassifier(n_neighbors=6)
최적의 index :  5


In [42]:
knn.predict(x_test)

array([2, 1, 0, 2, 0, 2, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 2, 1,
       0, 0, 2, 0, 0, 1, 1, 0, 2, 1, 0, 2, 2, 1, 0, 2])

In [43]:
knn.score(x_test, y_test)

0.9473684210526315

In [46]:
knn.fit(x_train, y_train)
print('최적의 parameter : ', knn.best_params_)
print('최고 교차 검증 점수 : ', knn.best_score_)    # x_train에 대한 R2
print('최고 성능 모델 : ', knn.best_estimator_)
print('최적의 index : ', knn.best_index_)

최적의 parameter :  {'n_neighbors': 6}
최고 교차 검증 점수 :  0.9557312252964426
최고 성능 모델 :  KNeighborsClassifier(n_neighbors=6)
최적의 index :  5


In [57]:
param_dt = {'max_depth':range(1,10),'max_leaf_nodes':range(1,10),'min_samples_leaf':range(1,10)}

dt = GridSearchCV(DecisionTreeClassifier(), param_dt, cv=5)
dt.fit(x_train, y_train)

GridSearchCV(cv=5, estimator=DecisionTreeClassifier(),
             param_grid={'max_depth': range(1, 10),
                         'max_leaf_nodes': range(1, 10),
                         'min_samples_leaf': range(1, 10)})

In [58]:
print('최적의 parameter : ', dt.best_params_)
print('최고 교차 검증 점수 : ', dt.best_score_)    # x_train에 대한 R2
print('최고 성능 모델 : ', dt.best_estimator_)
print('최적의 index : ', dt.best_index_)

최적의 parameter :  {'max_depth': 4, 'max_leaf_nodes': 7, 'min_samples_leaf': 2}
최고 교차 검증 점수 :  0.9731225296442687
최고 성능 모델 :  DecisionTreeClassifier(max_depth=4, max_leaf_nodes=7, min_samples_leaf=2)
최적의 index :  298


In [59]:
dt.predict(x_test)

array([2, 1, 0, 2, 0, 2, 0, 1, 1, 1, 2, 1, 1, 1, 1, 0, 1, 1, 0, 0, 2, 1,
       0, 0, 2, 0, 0, 1, 1, 0, 2, 1, 0, 1, 2, 1, 0, 2])

In [60]:
dt.score(x_test, y_test)

0.9473684210526315

In [69]:
param_svc = {'C':[0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9,0.08],'gamma':[0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.08,0.05],'kernel':['linear','poly','rbf']}

svc = GridSearchCV(SVC(), param_svc, cv=5)
svc.fit(x_train, y_train)

GridSearchCV(cv=5, estimator=SVC(),
             param_grid={'C': [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9,
                               0.08],
                         'gamma': [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.08,
                                   0.05],
                         'kernel': ['linear', 'poly', 'rbf']})

In [70]:
print(svc.best_estimator_)
print(svc.best_params_)
print(svc.best_score_)

SVC(C=0.5, gamma=0.1, kernel='linear')
{'C': 0.5, 'gamma': 0.1, 'kernel': 'linear'}
0.9640316205533598


In [71]:
svc.predict(x_test)

array([2, 1, 0, 2, 0, 2, 0, 1, 1, 1, 2, 1, 1, 1, 1, 0, 1, 1, 0, 0, 2, 1,
       0, 0, 2, 0, 0, 1, 1, 0, 2, 1, 0, 2, 2, 1, 0, 2])

In [72]:
svc.score(x_test, y_test)

0.9736842105263158