In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import KFold

In [2]:
x_data = np.array([[2,1],[2,3],[4,1],[5,6],[7,7],[8,9],[9,10],[6,7],[6,10],[2,8],[7,5]])

kf = KFold(n_splits=5)

In [3]:
for train_index, test_index in kf.split(x_data):
    print(train_index)
    print(test_index)

[ 3  4  5  6  7  8  9 10]
[0 1 2]
[ 0  1  2  5  6  7  8  9 10]
[3 4]
[ 0  1  2  3  4  7  8  9 10]
[5 6]
[ 0  1  2  3  4  5  6  9 10]
[7 8]
[0 1 2 3 4 5 6 7 8]
[ 9 10]


### K-Fold 교차검증 -> 회귀 문제에서 사용
- 학습 data와 테스트 data를 n_splits개의 세트로 나누어 검증하는 방법
- data set이 적을 때 train data를 늘리기 위해 사용
- 여러 개의 train, test data 짝으로 검증과정을 거침

In [4]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

In [17]:
x_data = np.array([[2,1],[2,3],[4,1],[5,6],[7,7],[8,9],[9,10],[6,7],[6,10],[2,8],[7,5]])
y_data = np.array([3,5,9,7,10,12,13,6,4,16,17])

In [18]:
model = LinearRegression()

train_scores = []
test_scores = []

kf = KFold(n_splits=5)
for train_index, test_index in kf.split(x_data):
    x_train = np.array(x_data)[train_index]
    y_train = np.array(y_data)[train_index]
    x_test = np.array(x_data)[test_index]
    y_test = np.array(y_data)[test_index]

    model_kf = LinearRegression()
    model_kf.fit(x_train, y_train)
    score = model_kf.score(x_train, y_train)    # R2
    train_scores.append(score)
    score = model_kf.score(x_test, y_test)
    test_scores.append(score)

train_scores, test_scores

([0.05213429135369019,
  0.14624601019193806,
  0.050945517946332064,
  0.39748376135823704,
  0.8389256888394099],
 [-11.322786978643151,
  -0.35618419140117474,
  -12.256602622244174,
  -62.91574296944087,
  -712.9578312315076])

In [19]:
np.array(train_scores).mean()

0.2971470539379214

In [20]:
np.array(test_scores).mean()

-159.9618295986474

R2값
- -, + 부호는 그래프의 기울기
- 절대값은 data를 잘 설명하는 정도(-1~1 사이의 값을 가짐) : 너무 커지거나 작아지면 data가 쓰레기라는 뜻