In [1]:
import numpy as np

In [4]:
arr = np.arange(0,51,2)
arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50])

In [6]:
arr = np.array(range(0,51,2))
arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50])

In [8]:
arr = np.zeros((4,4))
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [20]:
arr = arr.astype("int64")
arr

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]], dtype=int64)

In [18]:
arr = np.ones((10,10), dtype = np.int)
arr

C:\Users\user\AppData\Local\Temp\ipykernel_2140\2582669951.py:1: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  arr = np.ones((10,10), dtype = np.int)


array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [12]:
arr = np.full((7,7),7)
arr

array([[7, 7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7, 7]])

In [22]:
arr = np.arange(3,100,3)
arr

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48, 51,
       54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [23]:
arr.size

33

In [29]:
arr = arr.reshape(3,11)
arr

array([[ 3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33],
       [36, 39, 42, 45, 48, 51, 54, 57, 60, 63, 66],
       [69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99]])

In [28]:
arr.shape

(3, 11)

In [30]:
import random
from random import randint

In [34]:
arr = np.random.rand(6,4)
arr

array([[0.89005767, 0.88110887, 0.23619585, 0.25402626],
       [0.71335554, 0.81746164, 0.51448243, 0.99095802],
       [0.15564804, 0.35956054, 0.42563422, 0.73322563],
       [0.21729416, 0.69384844, 0.05784797, 0.8144318 ],
       [0.54500427, 0.2943047 , 0.4732375 , 0.05904679],
       [0.76215471, 0.14874297, 0.14641636, 0.55086902]])

In [43]:
arr = np.random.random((6,4))
arr

array([[0.40489039, 0.78918071, 0.69571657, 0.96801684],
       [0.0224945 , 0.74870648, 0.59886268, 0.70638905],
       [0.91631978, 0.41942808, 0.03026821, 0.37053137],
       [0.01828339, 0.54902381, 0.04558699, 0.57055963],
       [0.16467473, 0.46969846, 0.25192811, 0.49310938],
       [0.89651614, 0.09609782, 0.07010863, 0.70257189]])

In [35]:
arr = np.random.rand(5,5) * 100
arr

array([[28.6225284 ,  1.91865207,  5.33415218, 31.75619621, 16.28309547],
       [99.84255795, 79.56706088,  8.99246274, 46.77417515, 66.72008455],
       [90.14171373, 14.08972273, 33.50024822, 85.51830875, 72.96802629],
       [65.04191451, 68.3446483 , 96.33105896, 61.29734345, 17.49759662],
       [32.6118295 , 55.08467318, 53.38522045, 93.13194975, 74.6973373 ]])

In [40]:
arr = np.random.randint(1,100,(5,5))
arr

array([[75, 78,  7, 24, 14],
       [48, 59, 83, 88, 24],
       [45, 90, 72, 17,  8],
       [94, 57, 63, 63, 75],
       [92, 70, 55, 50,  5]])

In [41]:
arr = arr.astype("float64")
arr

array([[75., 78.,  7., 24., 14.],
       [48., 59., 83., 88., 24.],
       [45., 90., 72., 17.,  8.],
       [94., 57., 63., 63., 75.],
       [92., 70., 55., 50.,  5.]])