In [4]:
import numpy as np

In [4]:
arr = np.arange(0,51,2)
arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50])

In [6]:
arr = np.array(range(0,51,2))
arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50])

In [8]:
arr = np.zeros((4,4))
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [20]:
arr = arr.astype("int64")
arr

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]], dtype=int64)

In [18]:
arr = np.ones((10,10), dtype = np.int)
arr

C:\Users\user\AppData\Local\Temp\ipykernel_2140\2582669951.py:1: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  arr = np.ones((10,10), dtype = np.int)


array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [12]:
arr = np.full((7,7),7)
arr

array([[7, 7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7, 7]])

In [22]:
arr = np.arange(3,100,3)
arr

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48, 51,
       54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [23]:
arr.size

33

In [29]:
arr = arr.reshape(3,11)
arr

array([[ 3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33],
       [36, 39, 42, 45, 48, 51, 54, 57, 60, 63, 66],
       [69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99]])

In [28]:
arr.shape

(3, 11)

In [30]:
import random
from random import randint

In [34]:
arr = np.random.rand(6,4)
arr

array([[0.89005767, 0.88110887, 0.23619585, 0.25402626],
       [0.71335554, 0.81746164, 0.51448243, 0.99095802],
       [0.15564804, 0.35956054, 0.42563422, 0.73322563],
       [0.21729416, 0.69384844, 0.05784797, 0.8144318 ],
       [0.54500427, 0.2943047 , 0.4732375 , 0.05904679],
       [0.76215471, 0.14874297, 0.14641636, 0.55086902]])

In [43]:
arr = np.random.random((6,4))
arr

array([[0.40489039, 0.78918071, 0.69571657, 0.96801684],
       [0.0224945 , 0.74870648, 0.59886268, 0.70638905],
       [0.91631978, 0.41942808, 0.03026821, 0.37053137],
       [0.01828339, 0.54902381, 0.04558699, 0.57055963],
       [0.16467473, 0.46969846, 0.25192811, 0.49310938],
       [0.89651614, 0.09609782, 0.07010863, 0.70257189]])

In [7]:
arr = np.random.rand(5,5) * 100
arr

array([[43.22985311, 48.5588871 , 30.32506338, 60.49321844, 46.76099992],
       [ 4.57104325, 95.05814538, 84.47457266, 53.00717598, 42.12093408],
       [90.40322056, 44.83019724, 63.92749275,  5.20189601, 72.1815008 ],
       [ 3.01146878, 46.72520822, 62.40921396, 73.6271397 , 67.84315869],
       [ 3.45393602, 32.02377854, 63.46887989, 10.95139314, 84.66315621]])

In [40]:
arr = np.random.randint(1,100,(5,5))
arr

array([[75, 78,  7, 24, 14],
       [48, 59, 83, 88, 24],
       [45, 90, 72, 17,  8],
       [94, 57, 63, 63, 75],
       [92, 70, 55, 50,  5]])

In [8]:
arr = arr.astype("int64")
arr

array([[43, 48, 30, 60, 46],
       [ 4, 95, 84, 53, 42],
       [90, 44, 63,  5, 72],
       [ 3, 46, 62, 73, 67],
       [ 3, 32, 63, 10, 84]], dtype=int64)

In [15]:
x = np.arange(10).reshape(2,5)
x[:,3:]

array([[3, 4],
       [8, 9]])

In [17]:
x[1,1:4]

array([6, 7, 8])

In [30]:
y = np.arange(15).reshape(3,5)
y[:,3], y[:,3:4], y[1], y[:2,1:4]

(array([ 3,  8, 13]),
 array([[ 3],
        [ 8],
        [13]]),
 array([5, 6, 7, 8, 9]),
 array([[1, 2, 3],
        [6, 7, 8]]))

In [32]:
arr = np.arange(1,13).reshape(3,4)
arr[arr<=5]

array([1, 2, 3, 4, 5])

In [34]:
arr[(arr % 3) == 0]

array([ 3,  6,  9, 12])

In [35]:
import random

In [37]:
x = np.random.randint(1,100,10)
x

array([82,  4, 84,  9, 66, 76, 13, 72, 40, 63])

In [41]:
x[((x % 2) == 0) & (x >= 60)]

array([82, 84, 66, 76, 72])

In [39]:
x[x >= 60]

array([82, 84, 66, 76, 72, 63])

In [44]:
x[(30 < x) & (x < 70)]

array([66, 40, 63])

In [43]:
x[(x > 60) | (x%2 == 1)]

array([82, 84,  9, 66, 76, 13, 72, 63])

In [45]:
temp = np.array(
        [23.9, 24.4, 24.1, 25.4, 27.6, 29.7,
         26.7, 25.1, 25.0, 22.7, 21.9, 23.6, 
         24.9, 25.9, 23.8, 24.7, 25.6, 26.9, 
         28.6, 28.0, 25.1, 26.7, 28.1, 26.5, 
         26.3, 25.9, 28.4, 26.1, 27.5, 28.1, 25.8])

In [48]:
temp.size, len(temp)

(31, 31)

In [50]:
temp[temp>25].size, len(temp[temp>25])

(21, 21)

In [63]:
temp[temp>25].mean()
# .astype("int64")

26.857142857142858

In [64]:
np.sum(temp>25)

21