In [1]:
import numpy as np

#### BMI 구하기
    delimiter : 구분기호

In [3]:
data = np.loadtxt("height_weight.txt", delimiter = ",")
data

array([[175.2, 180.3, 175. , 169.2, 185.2, 188. , 177.6, 178.2, 177. ,
        179. ],
       [ 65.6,  88. ,  79.2,  69.3,  55. ,  71.2,  73. ,  68.9,  74. ,
         82. ]])

In [6]:
# data를 불러 왔을 때 모양을 알기 위해 제일 먼저 shape 해줌
data.shape, data.size

((2, 10), 20)

In [9]:
# data를 키와 몸무게로 나누기
height_cm = data[0]
weight_kg = data[1]
len(height_cm), len(weight_kg), height_cm, weight_kg

(10,
 10,
 array([175.2, 180.3, 175. , 169.2, 185.2, 188. , 177.6, 178.2, 177. ,
        179. ]),
 array([65.6, 88. , 79.2, 69.3, 55. , 71.2, 73. , 68.9, 74. , 82. ]))

In [8]:
height_m = height_cm/100
height_m

array([1.752, 1.803, 1.75 , 1.692, 1.852, 1.88 , 1.776, 1.782, 1.77 ,
       1.79 ])

In [10]:
BMI = weight_kg/(height_m**2)
BMI

array([21.37153104, 27.07018468, 25.86122449, 24.20652885, 16.03543423,
       20.14486193, 23.14392095, 21.69720651, 23.62028791, 25.59220998])

#### ID, 평점

In [22]:
ratings_data = np.loadtxt("ratings.txt", delimiter = "::", dtype = "int")
ratings_data

array([[        1,      1193,         5, 978300760],
       [        1,       661,         3, 978302109],
       [        1,       914,         3, 978301968],
       ...,
       [     6040,       562,         5, 956704746],
       [     6040,      1096,         4, 956715648],
       [     6040,      1097,         4, 956715569]])

In [13]:
ratings_data.shape, ratings_data.size, ratings_data.ndim

((1000209, 4), 4000836, 2)

In [31]:
ratings_data[ratings_data[:,0] == 1]

array([[        1,      1193,         5, 978300760],
       [        1,       661,         3, 978302109],
       [        1,       914,         3, 978301968],
       [        1,      3408,         4, 978300275],
       [        1,      2355,         5, 978824291],
       [        1,      1197,         3, 978302268],
       [        1,      1287,         5, 978302039],
       [        1,      2804,         5, 978300719],
       [        1,       594,         4, 978302268],
       [        1,       919,         4, 978301368],
       [        1,       595,         5, 978824268],
       [        1,       938,         4, 978301752],
       [        1,      2398,         4, 978302281],
       [        1,      2918,         4, 978302124],
       [        1,      1035,         5, 978301753],
       [        1,      2791,         4, 978302188],
       [        1,      2687,         3, 978824268],
       [        1,      2018,         4, 978301777],
       [        1,      3105,         5, 97830

In [35]:
ratings_data[:,0]

array([   1,    1,    1, ..., 6040, 6040, 6040])

In [47]:
reviews = ratings_data[:,2]
np.mean(reviews), len(reviews)

(3.581564453029317, 1000209)

In [48]:
first = ratings_data[ratings_data[:,0] == 1]
print(first)
print(first[:,2])
print(first[:,2].mean())

[[        1      1193         5 978300760]
 [        1       661         3 978302109]
 [        1       914         3 978301968]
 [        1      3408         4 978300275]
 [        1      2355         5 978824291]
 [        1      1197         3 978302268]
 [        1      1287         5 978302039]
 [        1      2804         5 978300719]
 [        1       594         4 978302268]
 [        1       919         4 978301368]
 [        1       595         5 978824268]
 [        1       938         4 978301752]
 [        1      2398         4 978302281]
 [        1      2918         4 978302124]
 [        1      1035         5 978301753]
 [        1      2791         4 978302188]
 [        1      2687         3 978824268]
 [        1      2018         4 978301777]
 [        1      3105         5 978301713]
 [        1      2797         4 978302039]
 [        1      2321         3 978302205]
 [        1       720         3 978300760]
 [        1      1270         5 978300055]
 [        1