In [1]:
import numpy as np
import random

#### 1차원 정렬


In [3]:
arr = np.array([1,10,5,8,2,4,3,6,8,7,9])
arr.sort()  # data 원본을 변경하는건 안좋기 때문에 사용하는거 추천x 
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  8,  9, 10])

In [8]:
arr1 = np.array([1,10,5,8,2,4,3,6,8,7,9])
np.sort(arr1)   # 원본은 변경 안됨

array([ 1,  2,  3,  4,  5,  6,  7,  8,  8,  9, 10])

In [5]:
arr = np.array([1,10,5,8,2,4,3,6,8,7,9])
np.sort(arr)[::-1]

array([10,  9,  8,  8,  7,  6,  5,  4,  3,  2,  1])

In [7]:
arr = np.array([1,10,5,8,2,4,3,6,8,7,9])
arr.sort()
arr[::-1]

array([10,  9,  8,  8,  7,  6,  5,  4,  3,  2,  1])

#### n차원 정렬


In [9]:
arr2d=np.array([[5,2,7,8],
              [4,3,2,1],
              [10,9,12,11]])

In [13]:
arr2d.shape

(3, 4)

In [10]:
# 열 정렬(왼쪽 -> 오른쪽)
np.sort(arr2d, axis=1)

array([[ 2,  5,  7,  8],
       [ 1,  2,  3,  4],
       [ 9, 10, 11, 12]])

In [11]:
# 행 정렬(위 -> 아래)
np.sort(arr2d, axis=0)

array([[ 4,  2,  2,  1],
       [ 5,  3,  7,  8],
       [10,  9, 12, 11]])

In [21]:
y = np.random.randint(0,100,(3,5))
print(y)
print(np.sum(y))    # y.sum()
print(np.mean(y))
print(np.max(y))
print(np.min(y))
print(np.var(y))   # 분산
print(np.median(y))    # 중앙값
print(np.std(y))    # 표준편차

[[41 78 27 75 96]
 [74 73 65 74 13]
 [65 60 24 23 65]]
853
56.86666666666667
96
13
577.1822222222221
65.0
24.02461700469379
